//go:build !ignore_autogenerated

/*
Copyright 2026.

SPDX-License-Identifier: AGPL-3.0-only
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRun) DeepCopyInto(out *AgentRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRun.
func (in *AgentRun) DeepCopy() *AgentRun {
	if in == nil {
		return nil
	}
	out := new(AgentRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunActivity) DeepCopyInto(out *AgentRunActivity) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunActivity.
func (in *AgentRunActivity) DeepCopy() *AgentRunActivity {
	if in == nil {
		return nil
	}
	out := new(AgentRunActivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunArtifacts) DeepCopyInto(out *AgentRunArtifacts) {
	*out = *in
	if in.PlanRef != nil {
		in, out := &in.PlanRef, &out.PlanRef
		*out = new(ArtifactRef)
		**out = **in
	}
	if in.ReviewSummaryRef != nil {
		in, out := &in.ReviewSummaryRef, &out.ReviewSummaryRef
		*out = new(ArtifactRef)
		**out = **in
	}
	if in.PullRequestURLs != nil {
		in, out := &in.PullRequestURLs, &out.PullRequestURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MetaHarnessTraceRef != nil {
		in, out := &in.MetaHarnessTraceRef, &out.MetaHarnessTraceRef
		*out = new(ArtifactRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunArtifacts.
func (in *AgentRunArtifacts) DeepCopy() *AgentRunArtifacts {
	if in == nil {
		return nil
	}
	out := new(AgentRunArtifacts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunChatMessage) DeepCopyInto(out *AgentRunChatMessage) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunChatMessage.
func (in *AgentRunChatMessage) DeepCopy() *AgentRunChatMessage {
	if in == nil {
		return nil
	}
	out := new(AgentRunChatMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunChildStatus) DeepCopyInto(out *AgentRunChildStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunChildStatus.
func (in *AgentRunChildStatus) DeepCopy() *AgentRunChildStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunChildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunCompletionPolicy) DeepCopyInto(out *AgentRunCompletionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunCompletionPolicy.
func (in *AgentRunCompletionPolicy) DeepCopy() *AgentRunCompletionPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentRunCompletionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunContext) DeepCopyInto(out *AgentRunContext) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(ProjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunContext.
func (in *AgentRunContext) DeepCopy() *AgentRunContext {
	if in == nil {
		return nil
	}
	out := new(AgentRunContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunDelegationPolicy) DeepCopyInto(out *AgentRunDelegationPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunDelegationPolicy.
func (in *AgentRunDelegationPolicy) DeepCopy() *AgentRunDelegationPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentRunDelegationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunLimits) DeepCopyInto(out *AgentRunLimits) {
	*out = *in
	out.MaxRuntime = in.MaxRuntime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunLimits.
func (in *AgentRunLimits) DeepCopy() *AgentRunLimits {
	if in == nil {
		return nil
	}
	out := new(AgentRunLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunList) DeepCopyInto(out *AgentRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunList.
func (in *AgentRunList) DeepCopy() *AgentRunList {
	if in == nil {
		return nil
	}
	out := new(AgentRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunMetrics) DeepCopyInto(out *AgentRunMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunMetrics.
func (in *AgentRunMetrics) DeepCopy() *AgentRunMetrics {
	if in == nil {
		return nil
	}
	out := new(AgentRunMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunOverseerSpec) DeepCopyInto(out *AgentRunOverseerSpec) {
	*out = *in
	if in.ModeRef != nil {
		in, out := &in.ModeRef, &out.ModeRef
		*out = new(ModeRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunOverseerSpec.
func (in *AgentRunOverseerSpec) DeepCopy() *AgentRunOverseerSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunOverseerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunOverseerStatus) DeepCopyInto(out *AgentRunOverseerStatus) {
	*out = *in
	if in.LastVerdictTime != nil {
		in, out := &in.LastVerdictTime, &out.LastVerdictTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunOverseerStatus.
func (in *AgentRunOverseerStatus) DeepCopy() *AgentRunOverseerStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunOverseerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunQueueStatus) DeepCopyInto(out *AgentRunQueueStatus) {
	*out = *in
	if in.AdmittedAt != nil {
		in, out := &in.AdmittedAt, &out.AdmittedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunQueueStatus.
func (in *AgentRunQueueStatus) DeepCopy() *AgentRunQueueStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunQueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunResolvedPolicy) DeepCopyInto(out *AgentRunResolvedPolicy) {
	*out = *in
	if in.ResolvedAgentKinds != nil {
		in, out := &in.ResolvedAgentKinds, &out.ResolvedAgentKinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResolvedSkills != nil {
		in, out := &in.ResolvedSkills, &out.ResolvedSkills
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResolvedMCPServers != nil {
		in, out := &in.ResolvedMCPServers, &out.ResolvedMCPServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunResolvedPolicy.
func (in *AgentRunResolvedPolicy) DeepCopy() *AgentRunResolvedPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentRunResolvedPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunRoleModelOverride) DeepCopyInto(out *AgentRunRoleModelOverride) {
	*out = *in
	if in.ModelsByProvider != nil {
		in, out := &in.ModelsByProvider, &out.ModelsByProvider
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunRoleModelOverride.
func (in *AgentRunRoleModelOverride) DeepCopy() *AgentRunRoleModelOverride {
	if in == nil {
		return nil
	}
	out := new(AgentRunRoleModelOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunSandboxStatus) DeepCopyInto(out *AgentRunSandboxStatus) {
	*out = *in
	if in.ClaimRef != nil {
		in, out := &in.ClaimRef, &out.ClaimRef
		*out = new(NamedRef)
		**out = **in
	}
	if in.SandboxRef != nil {
		in, out := &in.SandboxRef, &out.SandboxRef
		*out = new(NamedRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunSandboxStatus.
func (in *AgentRunSandboxStatus) DeepCopy() *AgentRunSandboxStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunSandboxStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunSecrets) DeepCopyInto(out *AgentRunSecrets) {
	*out = *in
	if in.ProviderKeys != nil {
		in, out := &in.ProviderKeys, &out.ProviderKeys
		*out = make([]ProviderKeyRef, len(*in))
		copy(*out, *in)
	}
	if in.ProviderOAuthSecrets != nil {
		in, out := &in.ProviderOAuthSecrets, &out.ProviderOAuthSecrets
		*out = make([]ProviderOAuthSecretRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunSecrets.
func (in *AgentRunSecrets) DeepCopy() *AgentRunSecrets {
	if in == nil {
		return nil
	}
	out := new(AgentRunSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunSpec) DeepCopyInto(out *AgentRunSpec) {
	*out = *in
	in.Trigger.DeepCopyInto(&out.Trigger)
	in.Repository.DeepCopyInto(&out.Repository)
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = new(AgentRunContext)
		(*in).DeepCopyInto(*out)
	}
	if in.Team != nil {
		in, out := &in.Team, &out.Team
		*out = new(AgentRunTeamSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Overseer != nil {
		in, out := &in.Overseer, &out.Overseer
		*out = new(AgentRunOverseerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ModeRef != nil {
		in, out := &in.ModeRef, &out.ModeRef
		*out = new(ModeRef)
		**out = **in
	}
	if in.RoleModelOverrides != nil {
		in, out := &in.RoleModelOverrides, &out.RoleModelOverrides
		*out = make([]AgentRunRoleModelOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SpecArtifactRef != nil {
		in, out := &in.SpecArtifactRef, &out.SpecArtifactRef
		*out = new(ArtifactRef)
		**out = **in
	}
	if in.RuntimeProfileRef != nil {
		in, out := &in.RuntimeProfileRef, &out.RuntimeProfileRef
		*out = new(NamedRef)
		**out = **in
	}
	if in.MCPPolicyRef != nil {
		in, out := &in.MCPPolicyRef, &out.MCPPolicyRef
		*out = new(NamedRef)
		**out = **in
	}
	if in.GuardrailPolicyRef != nil {
		in, out := &in.GuardrailPolicyRef, &out.GuardrailPolicyRef
		*out = new(NamedRef)
		**out = **in
	}
	if in.MCPServerRefs != nil {
		in, out := &in.MCPServerRefs, &out.MCPServerRefs
		*out = make([]NamedRef, len(*in))
		copy(*out, *in)
	}
	if in.SkillRefs != nil {
		in, out := &in.SkillRefs, &out.SkillRefs
		*out = make([]NamedRef, len(*in))
		copy(*out, *in)
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(AgentRunLimits)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(AgentRunSecrets)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunSpec.
func (in *AgentRunSpec) DeepCopy() *AgentRunSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunStatus) DeepCopyInto(out *AgentRunStatus) {
	*out = *in
	if in.Queue != nil {
		in, out := &in.Queue, &out.Queue
		*out = new(AgentRunQueueStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Sandbox != nil {
		in, out := &in.Sandbox, &out.Sandbox
		*out = new(AgentRunSandboxStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = new(AgentRunArtifacts)
		(*in).DeepCopyInto(*out)
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(AgentRunResolvedPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(AgentRunMetrics)
		**out = **in
	}
	if in.TeamSummary != nil {
		in, out := &in.TeamSummary, &out.TeamSummary
		*out = new(AgentRunTeamSummary)
		**out = **in
	}
	if in.OverseerSummary != nil {
		in, out := &in.OverseerSummary, &out.OverseerSummary
		*out = new(AgentRunOverseerStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]AgentRunChildStatus, len(*in))
		copy(*out, *in)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.LastWakeTime != nil {
		in, out := &in.LastWakeTime, &out.LastWakeTime
		*out = (*in).DeepCopy()
	}
	if in.ModeSnapshot != nil {
		in, out := &in.ModeSnapshot, &out.ModeSnapshot
		*out = new(ModeTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunStatus.
func (in *AgentRunStatus) DeepCopy() *AgentRunStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunTeamRuntime) DeepCopyInto(out *AgentRunTeamRuntime) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunTeamRuntime.
func (in *AgentRunTeamRuntime) DeepCopy() *AgentRunTeamRuntime {
	if in == nil {
		return nil
	}
	out := new(AgentRunTeamRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRunTeamRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunTeamRuntimeList) DeepCopyInto(out *AgentRunTeamRuntimeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentRunTeamRuntime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunTeamRuntimeList.
func (in *AgentRunTeamRuntimeList) DeepCopy() *AgentRunTeamRuntimeList {
	if in == nil {
		return nil
	}
	out := new(AgentRunTeamRuntimeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRunTeamRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunTeamRuntimeSpec) DeepCopyInto(out *AgentRunTeamRuntimeSpec) {
	*out = *in
	out.ParentRef = in.ParentRef
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]TeamRuntimeTaskInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DelegationPolicy != nil {
		in, out := &in.DelegationPolicy, &out.DelegationPolicy
		*out = new(AgentRunDelegationPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunTeamRuntimeSpec.
func (in *AgentRunTeamRuntimeSpec) DeepCopy() *AgentRunTeamRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunTeamRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunTeamRuntimeStatus) DeepCopyInto(out *AgentRunTeamRuntimeStatus) {
	*out = *in
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]TeamRuntimeTaskInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EventCheckpoint != nil {
		in, out := &in.EventCheckpoint, &out.EventCheckpoint
		*out = new(TeamRuntimeEventCheckpoint)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunTeamRuntimeStatus.
func (in *AgentRunTeamRuntimeStatus) DeepCopy() *AgentRunTeamRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunTeamRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunTeamSpec) DeepCopyInto(out *AgentRunTeamSpec) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]AgentRunTeamStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DelegationPolicy != nil {
		in, out := &in.DelegationPolicy, &out.DelegationPolicy
		*out = new(AgentRunDelegationPolicy)
		**out = **in
	}
	if in.CompletionPolicy != nil {
		in, out := &in.CompletionPolicy, &out.CompletionPolicy
		*out = new(AgentRunCompletionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunTeamSpec.
func (in *AgentRunTeamSpec) DeepCopy() *AgentRunTeamSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunTeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunTeamStep) DeepCopyInto(out *AgentRunTeamStep) {
	*out = *in
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]AgentRunTeamTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunTeamStep.
func (in *AgentRunTeamStep) DeepCopy() *AgentRunTeamStep {
	if in == nil {
		return nil
	}
	out := new(AgentRunTeamStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunTeamSummary) DeepCopyInto(out *AgentRunTeamSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunTeamSummary.
func (in *AgentRunTeamSummary) DeepCopy() *AgentRunTeamSummary {
	if in == nil {
		return nil
	}
	out := new(AgentRunTeamSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunTeamTask) DeepCopyInto(out *AgentRunTeamTask) {
	*out = *in
	if in.RuntimeProfileRef != nil {
		in, out := &in.RuntimeProfileRef, &out.RuntimeProfileRef
		*out = new(NamedRef)
		**out = **in
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunTeamTask.
func (in *AgentRunTeamTask) DeepCopy() *AgentRunTeamTask {
	if in == nil {
		return nil
	}
	out := new(AgentRunTeamTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactRef) DeepCopyInto(out *ArtifactRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactRef.
func (in *ArtifactRef) DeepCopy() *ArtifactRef {
	if in == nil {
		return nil
	}
	out := new(ArtifactRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalRef) DeepCopyInto(out *ExternalRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalRef.
func (in *ExternalRef) DeepCopy() *ExternalRef {
	if in == nil {
		return nil
	}
	out := new(ExternalRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailPolicy) DeepCopyInto(out *GuardrailPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailPolicy.
func (in *GuardrailPolicy) DeepCopy() *GuardrailPolicy {
	if in == nil {
		return nil
	}
	out := new(GuardrailPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuardrailPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailPolicyList) DeepCopyInto(out *GuardrailPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GuardrailPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailPolicyList.
func (in *GuardrailPolicyList) DeepCopy() *GuardrailPolicyList {
	if in == nil {
		return nil
	}
	out := new(GuardrailPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuardrailPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailPolicySpec) DeepCopyInto(out *GuardrailPolicySpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]GuardrailRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailPolicySpec.
func (in *GuardrailPolicySpec) DeepCopy() *GuardrailPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GuardrailPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailPolicyStatus) DeepCopyInto(out *GuardrailPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailPolicyStatus.
func (in *GuardrailPolicyStatus) DeepCopy() *GuardrailPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GuardrailPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailRule) DeepCopyInto(out *GuardrailRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailRule.
func (in *GuardrailRule) DeepCopy() *GuardrailRule {
	if in == nil {
		return nil
	}
	out := new(GuardrailRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPAllowedServer) DeepCopyInto(out *MCPAllowedServer) {
	*out = *in
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPAllowedServer.
func (in *MCPAllowedServer) DeepCopy() *MCPAllowedServer {
	if in == nil {
		return nil
	}
	out := new(MCPAllowedServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPBreakGlass) DeepCopyInto(out *MCPBreakGlass) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPBreakGlass.
func (in *MCPBreakGlass) DeepCopy() *MCPBreakGlass {
	if in == nil {
		return nil
	}
	out := new(MCPBreakGlass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPPolicy) DeepCopyInto(out *MCPPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPPolicy.
func (in *MCPPolicy) DeepCopy() *MCPPolicy {
	if in == nil {
		return nil
	}
	out := new(MCPPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPPolicyList) DeepCopyInto(out *MCPPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPPolicyList.
func (in *MCPPolicyList) DeepCopy() *MCPPolicyList {
	if in == nil {
		return nil
	}
	out := new(MCPPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPPolicySpec) DeepCopyInto(out *MCPPolicySpec) {
	*out = *in
	if in.AllowedServers != nil {
		in, out := &in.AllowedServers, &out.AllowedServers
		*out = make([]MCPAllowedServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BreakGlass != nil {
		in, out := &in.BreakGlass, &out.BreakGlass
		*out = new(MCPBreakGlass)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPPolicySpec.
func (in *MCPPolicySpec) DeepCopy() *MCPPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MCPPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPPolicyStatus) DeepCopyInto(out *MCPPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPPolicyStatus.
func (in *MCPPolicyStatus) DeepCopy() *MCPPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MCPPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServer) DeepCopyInto(out *MCPServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServer.
func (in *MCPServer) DeepCopy() *MCPServer {
	if in == nil {
		return nil
	}
	out := new(MCPServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerConfig) DeepCopyInto(out *MCPServerConfig) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AllowEnv != nil {
		in, out := &in.AllowEnv, &out.AllowEnv
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecretEnv != nil {
		in, out := &in.SecretEnv, &out.SecretEnv
		*out = make([]MCPServerSecretEnv, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerConfig.
func (in *MCPServerConfig) DeepCopy() *MCPServerConfig {
	if in == nil {
		return nil
	}
	out := new(MCPServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerList) DeepCopyInto(out *MCPServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerList.
func (in *MCPServerList) DeepCopy() *MCPServerList {
	if in == nil {
		return nil
	}
	out := new(MCPServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerSecretEnv) DeepCopyInto(out *MCPServerSecretEnv) {
	*out = *in
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerSecretEnv.
func (in *MCPServerSecretEnv) DeepCopy() *MCPServerSecretEnv {
	if in == nil {
		return nil
	}
	out := new(MCPServerSecretEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerSpec) DeepCopyInto(out *MCPServerSpec) {
	*out = *in
	if in.MCPServerConfig != nil {
		in, out := &in.MCPServerConfig, &out.MCPServerConfig
		*out = new(MCPServerConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerSpec.
func (in *MCPServerSpec) DeepCopy() *MCPServerSpec {
	if in == nil {
		return nil
	}
	out := new(MCPServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerStatus) DeepCopyInto(out *MCPServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerStatus.
func (in *MCPServerStatus) DeepCopy() *MCPServerStatus {
	if in == nil {
		return nil
	}
	out := new(MCPServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeConstraints) DeepCopyInto(out *ModeConstraints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeConstraints.
func (in *ModeConstraints) DeepCopy() *ModeConstraints {
	if in == nil {
		return nil
	}
	out := new(ModeConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeRef) DeepCopyInto(out *ModeRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeRef.
func (in *ModeRef) DeepCopy() *ModeRef {
	if in == nil {
		return nil
	}
	out := new(ModeRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeTemplate) DeepCopyInto(out *ModeTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeTemplate.
func (in *ModeTemplate) DeepCopy() *ModeTemplate {
	if in == nil {
		return nil
	}
	out := new(ModeTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModeTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeTemplateList) DeepCopyInto(out *ModeTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModeTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeTemplateList.
func (in *ModeTemplateList) DeepCopy() *ModeTemplateList {
	if in == nil {
		return nil
	}
	out := new(ModeTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModeTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeTemplateSpec) DeepCopyInto(out *ModeTemplateSpec) {
	*out = *in
	if in.Constraints != nil {
		in, out := &in.Constraints, &out.Constraints
		*out = new(ModeConstraints)
		**out = **in
	}
	if in.AllowedMutatingTools != nil {
		in, out := &in.AllowedMutatingTools, &out.AllowedMutatingTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultMCPServerRefs != nil {
		in, out := &in.DefaultMCPServerRefs, &out.DefaultMCPServerRefs
		*out = make([]NamedRef, len(*in))
		copy(*out, *in)
	}
	if in.DefaultSkillRefs != nil {
		in, out := &in.DefaultSkillRefs, &out.DefaultSkillRefs
		*out = make([]NamedRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeTemplateSpec.
func (in *ModeTemplateSpec) DeepCopy() *ModeTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ModeTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeTemplateStatus) DeepCopyInto(out *ModeTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeTemplateStatus.
func (in *ModeTemplateStatus) DeepCopy() *ModeTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(ModeTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeTransitionEvent) DeepCopyInto(out *ModeTransitionEvent) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeTransitionEvent.
func (in *ModeTransitionEvent) DeepCopy() *ModeTransitionEvent {
	if in == nil {
		return nil
	}
	out := new(ModeTransitionEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedRef) DeepCopyInto(out *NamedRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedRef.
func (in *NamedRef) DeepCopy() *NamedRef {
	if in == nil {
		return nil
	}
	out := new(NamedRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverseerInputResponse) DeepCopyInto(out *OverseerInputResponse) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverseerInputResponse.
func (in *OverseerInputResponse) DeepCopy() *OverseerInputResponse {
	if in == nil {
		return nil
	}
	out := new(OverseerInputResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectRef) DeepCopyInto(out *ProjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectRef.
func (in *ProjectRef) DeepCopy() *ProjectRef {
	if in == nil {
		return nil
	}
	out := new(ProjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderKeyRef) DeepCopyInto(out *ProviderKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderKeyRef.
func (in *ProviderKeyRef) DeepCopy() *ProviderKeyRef {
	if in == nil {
		return nil
	}
	out := new(ProviderKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderOAuthSecretRef) DeepCopyInto(out *ProviderOAuthSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderOAuthSecretRef.
func (in *ProviderOAuthSecretRef) DeepCopy() *ProviderOAuthSecretRef {
	if in == nil {
		return nil
	}
	out := new(ProviderOAuthSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryContext) DeepCopyInto(out *RepositoryContext) {
	*out = *in
	if in.AdditionalRepos != nil {
		in, out := &in.AdditionalRepos, &out.AdditionalRepos
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryContext.
func (in *RepositoryContext) DeepCopy() *RepositoryContext {
	if in == nil {
		return nil
	}
	out := new(RepositoryContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleInstruction) DeepCopyInto(out *RoleInstruction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleInstruction.
func (in *RoleInstruction) DeepCopy() *RoleInstruction {
	if in == nil {
		return nil
	}
	out := new(RoleInstruction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleInstruction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleInstructionList) DeepCopyInto(out *RoleInstructionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RoleInstruction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleInstructionList.
func (in *RoleInstructionList) DeepCopy() *RoleInstructionList {
	if in == nil {
		return nil
	}
	out := new(RoleInstructionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleInstructionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleInstructionSpec) DeepCopyInto(out *RoleInstructionSpec) {
	*out = *in
	if in.ModelsByProvider != nil {
		in, out := &in.ModelsByProvider, &out.ModelsByProvider
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleInstructionSpec.
func (in *RoleInstructionSpec) DeepCopy() *RoleInstructionSpec {
	if in == nil {
		return nil
	}
	out := new(RoleInstructionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleInstructionStatus) DeepCopyInto(out *RoleInstructionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleInstructionStatus.
func (in *RoleInstructionStatus) DeepCopy() *RoleInstructionStatus {
	if in == nil {
		return nil
	}
	out := new(RoleInstructionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfile) DeepCopyInto(out *RuntimeProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfile.
func (in *RuntimeProfile) DeepCopy() *RuntimeProfile {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimeProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfileAdmission) DeepCopyInto(out *RuntimeProfileAdmission) {
	*out = *in
	out.StaleRunTimeout = in.StaleRunTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfileAdmission.
func (in *RuntimeProfileAdmission) DeepCopy() *RuntimeProfileAdmission {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfileAdmission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfileCommandSandbox) DeepCopyInto(out *RuntimeProfileCommandSandbox) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PathPrepend != nil {
		in, out := &in.PathPrepend, &out.PathPrepend
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PathAppend != nil {
		in, out := &in.PathAppend, &out.PathAppend
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraReadOnlyPaths != nil {
		in, out := &in.ExtraReadOnlyPaths, &out.ExtraReadOnlyPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraWritablePaths != nil {
		in, out := &in.ExtraWritablePaths, &out.ExtraWritablePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfileCommandSandbox.
func (in *RuntimeProfileCommandSandbox) DeepCopy() *RuntimeProfileCommandSandbox {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfileCommandSandbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfileList) DeepCopyInto(out *RuntimeProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuntimeProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfileList.
func (in *RuntimeProfileList) DeepCopy() *RuntimeProfileList {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimeProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfileSandbox) DeepCopyInto(out *RuntimeProfileSandbox) {
	*out = *in
	if in.SandboxTemplateRef != nil {
		in, out := &in.SandboxTemplateRef, &out.SandboxTemplateRef
		*out = new(NamedRef)
		**out = **in
	}
	if in.WarmPoolRef != nil {
		in, out := &in.WarmPoolRef, &out.WarmPoolRef
		*out = new(NamedRef)
		**out = **in
	}
	if in.CommandSandbox != nil {
		in, out := &in.CommandSandbox, &out.CommandSandbox
		*out = new(RuntimeProfileCommandSandbox)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfileSandbox.
func (in *RuntimeProfileSandbox) DeepCopy() *RuntimeProfileSandbox {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfileSandbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfileSecurity) DeepCopyInto(out *RuntimeProfileSecurity) {
	*out = *in
	out.DefaultTimeout = in.DefaultTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfileSecurity.
func (in *RuntimeProfileSecurity) DeepCopy() *RuntimeProfileSecurity {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfileSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfileSpec) DeepCopyInto(out *RuntimeProfileSpec) {
	*out = *in
	if in.Sandbox != nil {
		in, out := &in.Sandbox, &out.Sandbox
		*out = new(RuntimeProfileSandbox)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(RuntimeProfileSecurity)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Admission != nil {
		in, out := &in.Admission, &out.Admission
		*out = new(RuntimeProfileAdmission)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfileSpec.
func (in *RuntimeProfileSpec) DeepCopy() *RuntimeProfileSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfileStatus) DeepCopyInto(out *RuntimeProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfileStatus.
func (in *RuntimeProfileStatus) DeepCopy() *RuntimeProfileStatus {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Skill) DeepCopyInto(out *Skill) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Skill.
func (in *Skill) DeepCopy() *Skill {
	if in == nil {
		return nil
	}
	out := new(Skill)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Skill) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillGitSource) DeepCopyInto(out *SkillGitSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillGitSource.
func (in *SkillGitSource) DeepCopy() *SkillGitSource {
	if in == nil {
		return nil
	}
	out := new(SkillGitSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillInlineSource) DeepCopyInto(out *SkillInlineSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillInlineSource.
func (in *SkillInlineSource) DeepCopy() *SkillInlineSource {
	if in == nil {
		return nil
	}
	out := new(SkillInlineSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillList) DeepCopyInto(out *SkillList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Skill, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillList.
func (in *SkillList) DeepCopy() *SkillList {
	if in == nil {
		return nil
	}
	out := new(SkillList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SkillList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillRequires) DeepCopyInto(out *SkillRequires) {
	*out = *in
	if in.MCPServers != nil {
		in, out := &in.MCPServers, &out.MCPServers
		*out = make([]NamedRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillRequires.
func (in *SkillRequires) DeepCopy() *SkillRequires {
	if in == nil {
		return nil
	}
	out := new(SkillRequires)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillResolved) DeepCopyInto(out *SkillResolved) {
	*out = *in
	if in.SyncedAt != nil {
		in, out := &in.SyncedAt, &out.SyncedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillResolved.
func (in *SkillResolved) DeepCopy() *SkillResolved {
	if in == nil {
		return nil
	}
	out := new(SkillResolved)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillSource) DeepCopyInto(out *SkillSource) {
	*out = *in
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(SkillInlineSource)
		**out = **in
	}
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(SkillGitSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillSource.
func (in *SkillSource) DeepCopy() *SkillSource {
	if in == nil {
		return nil
	}
	out := new(SkillSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillSpec) DeepCopyInto(out *SkillSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = new(SkillRequires)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillSpec.
func (in *SkillSpec) DeepCopy() *SkillSpec {
	if in == nil {
		return nil
	}
	out := new(SkillSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillStatus) DeepCopyInto(out *SkillStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resolved != nil {
		in, out := &in.Resolved, &out.Resolved
		*out = new(SkillResolved)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillStatus.
func (in *SkillStatus) DeepCopy() *SkillStatus {
	if in == nil {
		return nil
	}
	out := new(SkillStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamRuntimeEventCheckpoint) DeepCopyInto(out *TeamRuntimeEventCheckpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamRuntimeEventCheckpoint.
func (in *TeamRuntimeEventCheckpoint) DeepCopy() *TeamRuntimeEventCheckpoint {
	if in == nil {
		return nil
	}
	out := new(TeamRuntimeEventCheckpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamRuntimeParentRef) DeepCopyInto(out *TeamRuntimeParentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamRuntimeParentRef.
func (in *TeamRuntimeParentRef) DeepCopy() *TeamRuntimeParentRef {
	if in == nil {
		return nil
	}
	out := new(TeamRuntimeParentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamRuntimeTaskInstance) DeepCopyInto(out *TeamRuntimeTaskInstance) {
	*out = *in
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LeaseExpiresAt != nil {
		in, out := &in.LeaseExpiresAt, &out.LeaseExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.LastHeartbeatAt != nil {
		in, out := &in.LastHeartbeatAt, &out.LastHeartbeatAt
		*out = (*in).DeepCopy()
	}
	if in.ClaimedAt != nil {
		in, out := &in.ClaimedAt, &out.ClaimedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamRuntimeTaskInstance.
func (in *TeamRuntimeTaskInstance) DeepCopy() *TeamRuntimeTaskInstance {
	if in == nil {
		return nil
	}
	out := new(TeamRuntimeTaskInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerRef) DeepCopyInto(out *TriggerRef) {
	*out = *in
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(ExternalRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerRef.
func (in *TriggerRef) DeepCopy() *TriggerRef {
	if in == nil {
		return nil
	}
	out := new(TriggerRef)
	in.DeepCopyInto(out)
	return out
}
