export type ImmunefiTarget = {
  name: string;
  displayName: string;
  repoUrl: string;
  workflowRef: string;
  policyPackRef: "bug-bounty";
  securityProgramRef: string;
};

export const IMMUNEFI_TARGET_CATALOG: readonly ImmunefiTarget[] = [
  {
    name: "immunefi-layerzero",
    displayName: "LayerZero",
    repoUrl: "https://github.com/LayerZero-Labs/LayerZero-v2",
    workflowRef: "bridge-l2-zk-security-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-layerzero",
  },
  {
    name: "immunefi-wormhole",
    displayName: "Wormhole",
    repoUrl: "https://github.com/wormhole-foundation/wormhole",
    workflowRef: "bridge-l2-zk-security-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-wormhole",
  },
  {
    name: "immunefi-hyperlane",
    displayName: "Hyperlane",
    repoUrl: "https://github.com/hyperlane-xyz/hyperlane-monorepo",
    workflowRef: "bridge-l2-zk-security-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-hyperlane",
  },
  {
    name: "immunefi-spark-alm-controller",
    displayName: "Spark ALM controller",
    repoUrl: "https://github.com/marsfoundation/spark-alm-controller",
    workflowRef: "smart-contract-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-spark",
  },
  {
    name: "immunefi-chainlink-ccip",
    displayName: "Chainlink CCIP",
    repoUrl: "https://github.com/smartcontractkit/chainlink-ccip",
    workflowRef: "bridge-l2-zk-security-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-chainlink",
  },
  {
    name: "immunefi-optimism",
    displayName: "Optimism",
    repoUrl: "https://github.com/ethereum-optimism/optimism",
    workflowRef: "blockchain-protocol-audit",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-optimism",
  },
  {
    name: "immunefi-zksync-era",
    displayName: "zkSync Era",
    repoUrl: "https://github.com/matter-labs/zksync-era",
    workflowRef: "bridge-l2-zk-security-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-zksync",
  },
  {
    name: "immunefi-arbitrum-token-bridge-contracts",
    displayName: "Arbitrum token-bridge-contracts",
    repoUrl: "https://github.com/OffchainLabs/token-bridge-contracts",
    workflowRef: "smart-contract-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-arbitrum",
  },
  {
    name: "immunefi-ethena",
    displayName: "Ethena",
    repoUrl: "https://github.com/ethena-labs/ethena-contracts",
    workflowRef: "smart-contract-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-ethena",
  },
  {
    name: "immunefi-sky-dss",
    displayName: "Sky DSS",
    repoUrl: "https://github.com/sky-ecosystem/dss",
    workflowRef: "smart-contract-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-sky",
  },
  {
    name: "immunefi-olympus-v3",
    displayName: "Olympus v3",
    repoUrl: "https://github.com/OlympusDAO/olympus-v3",
    workflowRef: "smart-contract-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-olympus",
  },
  {
    name: "immunefi-axelar-gmp-sdk-solidity",
    displayName: "Axelar GMP SDK Solidity",
    repoUrl: "https://github.com/axelarnetwork/axelar-gmp-sdk-solidity",
    workflowRef: "bridge-l2-zk-security-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-axelar",
  },
  {
    name: "immunefi-sui",
    displayName: "Sui",
    repoUrl: "https://github.com/MystenLabs/sui",
    workflowRef: "sui-move-security-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-sui",
  },
  {
    name: "immunefi-aptos",
    displayName: "Aptos",
    repoUrl: "https://github.com/aptos-labs/aptos-core",
    workflowRef: "aptos-move-security-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-aptos",
  },
  {
    name: "immunefi-polkadot-sdk",
    displayName: "Polkadot SDK",
    repoUrl: "https://github.com/paritytech/polkadot-sdk",
    workflowRef: "substrate-xcm-security-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-polkadot",
  },
  {
    name: "immunefi-thorchain-thornode",
    displayName: "THORChain thornode",
    repoUrl: "https://github.com/THORChain/THORNode",
    workflowRef: "blockchain-protocol-audit",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-thorchain",
  },
  {
    name: "immunefi-ton",
    displayName: "TON",
    repoUrl: "https://github.com/ton-blockchain/ton",
    workflowRef: "ton-security-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-ton",
  },
  {
    name: "immunefi-euler-v2",
    displayName: "Euler v2",
    repoUrl: "https://github.com/euler-xyz/euler-v2",
    workflowRef: "smart-contract-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-euler",
  },
  {
    name: "immunefi-ssv",
    displayName: "SSV",
    repoUrl: "https://github.com/bloxapp/ssv",
    workflowRef: "mpc-cryptography-security-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-ssv-network",
  },
  {
    name: "immunefi-osmosis",
    displayName: "Osmosis",
    repoUrl: "https://github.com/osmosis-labs/osmosis",
    workflowRef: "cosmos-ibc-security-review",
    policyPackRef: "bug-bounty",
    securityProgramRef: "immunefi-osmosis",
  },
];
