//go:build !ignore_autogenerated

/*
Copyright 2026.

SPDX-License-Identifier: AGPL-3.0-only
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	platformv1alpha1 "github.com/gratefulagents/gratefulagents/api/platform/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunDefaults) DeepCopyInto(out *AgentRunDefaults) {
	*out = *in
	if in.AdditionalRepos != nil {
		in, out := &in.AdditionalRepos, &out.AdditionalRepos
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedModels != nil {
		in, out := &in.AllowedModels, &out.AllowedModels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Timeout = in.Timeout
	in.Secrets.DeepCopyInto(&out.Secrets)
	if in.Team != nil {
		in, out := &in.Team, &out.Team
		*out = new(platformv1alpha1.AgentRunTeamSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ModeRef != nil {
		in, out := &in.ModeRef, &out.ModeRef
		*out = new(platformv1alpha1.ModeRef)
		**out = **in
	}
	if in.RuntimeProfileRef != nil {
		in, out := &in.RuntimeProfileRef, &out.RuntimeProfileRef
		*out = new(platformv1alpha1.NamedRef)
		**out = **in
	}
	if in.MCPPolicyRef != nil {
		in, out := &in.MCPPolicyRef, &out.MCPPolicyRef
		*out = new(platformv1alpha1.NamedRef)
		**out = **in
	}
	if in.MCPServerRefs != nil {
		in, out := &in.MCPServerRefs, &out.MCPServerRefs
		*out = make([]platformv1alpha1.NamedRef, len(*in))
		copy(*out, *in)
	}
	if in.SkillRefs != nil {
		in, out := &in.SkillRefs, &out.SkillRefs
		*out = make([]platformv1alpha1.NamedRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunDefaults.
func (in *AgentRunDefaults) DeepCopy() *AgentRunDefaults {
	if in == nil {
		return nil
	}
	out := new(AgentRunDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunSecrets) DeepCopyInto(out *AgentRunSecrets) {
	*out = *in
	if in.ProviderKeys != nil {
		in, out := &in.ProviderKeys, &out.ProviderKeys
		*out = make([]platformv1alpha1.ProviderKeyRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunSecrets.
func (in *AgentRunSecrets) DeepCopy() *AgentRunSecrets {
	if in == nil {
		return nil
	}
	out := new(AgentRunSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connection) DeepCopyInto(out *Connection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connection.
func (in *Connection) DeepCopy() *Connection {
	if in == nil {
		return nil
	}
	out := new(Connection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Connection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionList) DeepCopyInto(out *ConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Connection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionList.
func (in *ConnectionList) DeepCopy() *ConnectionList {
	if in == nil {
		return nil
	}
	out := new(ConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionRef) DeepCopyInto(out *ConnectionRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionRef.
func (in *ConnectionRef) DeepCopy() *ConnectionRef {
	if in == nil {
		return nil
	}
	out := new(ConnectionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSpec) DeepCopyInto(out *ConnectionSpec) {
	*out = *in
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(GitHubConnectionConfig)
		**out = **in
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackConnectionConfig)
		**out = **in
	}
	if in.Linear != nil {
		in, out := &in.Linear, &out.Linear
		*out = new(LinearConnectionConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSpec.
func (in *ConnectionSpec) DeepCopy() *ConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionStatus) DeepCopyInto(out *ConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStatus.
func (in *ConnectionStatus) DeepCopy() *ConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cron) DeepCopyInto(out *Cron) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cron.
func (in *Cron) DeepCopy() *Cron {
	if in == nil {
		return nil
	}
	out := new(Cron)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cron) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronList) DeepCopyInto(out *CronList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cron, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronList.
func (in *CronList) DeepCopy() *CronList {
	if in == nil {
		return nil
	}
	out := new(CronList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronProjectTriggerConfig) DeepCopyInto(out *CronProjectTriggerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronProjectTriggerConfig.
func (in *CronProjectTriggerConfig) DeepCopy() *CronProjectTriggerConfig {
	if in == nil {
		return nil
	}
	out := new(CronProjectTriggerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronSpec) DeepCopyInto(out *CronSpec) {
	*out = *in
	in.Defaults.DeepCopyInto(&out.Defaults)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronSpec.
func (in *CronSpec) DeepCopy() *CronSpec {
	if in == nil {
		return nil
	}
	out := new(CronSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronStatus) DeepCopyInto(out *CronStatus) {
	*out = *in
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.NextScheduleTime != nil {
		in, out := &in.NextScheduleTime, &out.NextScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronStatus.
func (in *CronStatus) DeepCopy() *CronStatus {
	if in == nil {
		return nil
	}
	out := new(CronStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubAppAuth) DeepCopyInto(out *GitHubAppAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubAppAuth.
func (in *GitHubAppAuth) DeepCopy() *GitHubAppAuth {
	if in == nil {
		return nil
	}
	out := new(GitHubAppAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubConnectionConfig) DeepCopyInto(out *GitHubConnectionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubConnectionConfig.
func (in *GitHubConnectionConfig) DeepCopy() *GitHubConnectionConfig {
	if in == nil {
		return nil
	}
	out := new(GitHubConnectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubObjectCursor) DeepCopyInto(out *GitHubObjectCursor) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubObjectCursor.
func (in *GitHubObjectCursor) DeepCopy() *GitHubObjectCursor {
	if in == nil {
		return nil
	}
	out := new(GitHubObjectCursor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubProjectTriggerConfig) DeepCopyInto(out *GitHubProjectTriggerConfig) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	out.PollInterval = in.PollInterval
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(TriggerAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.Maintainer != nil {
		in, out := &in.Maintainer, &out.Maintainer
		*out = new(MaintainerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubProjectTriggerConfig.
func (in *GitHubProjectTriggerConfig) DeepCopy() *GitHubProjectTriggerConfig {
	if in == nil {
		return nil
	}
	out := new(GitHubProjectTriggerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepository) DeepCopyInto(out *GitHubRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepository.
func (in *GitHubRepository) DeepCopy() *GitHubRepository {
	if in == nil {
		return nil
	}
	out := new(GitHubRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryList) DeepCopyInto(out *GitHubRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryList.
func (in *GitHubRepositoryList) DeepCopy() *GitHubRepositoryList {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositorySpec) DeepCopyInto(out *GitHubRepositorySpec) {
	*out = *in
	if in.GitHubApp != nil {
		in, out := &in.GitHubApp, &out.GitHubApp
		*out = new(GitHubAppAuth)
		**out = **in
	}
	out.PollInterval = in.PollInterval
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(TriggerAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.ReviewLoop != nil {
		in, out := &in.ReviewLoop, &out.ReviewLoop
		*out = new(ReviewLoopSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Maintainer != nil {
		in, out := &in.Maintainer, &out.Maintainer
		*out = new(MaintainerSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Defaults.DeepCopyInto(&out.Defaults)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositorySpec.
func (in *GitHubRepositorySpec) DeepCopy() *GitHubRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryStatus) DeepCopyInto(out *GitHubRepositoryStatus) {
	*out = *in
	if in.LastPollTime != nil {
		in, out := &in.LastPollTime, &out.LastPollTime
		*out = (*in).DeepCopy()
	}
	if in.ProcessedIssueIDs != nil {
		in, out := &in.ProcessedIssueIDs, &out.ProcessedIssueIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Maintainer != nil {
		in, out := &in.Maintainer, &out.Maintainer
		*out = new(MaintainerStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryStatus.
func (in *GitHubRepositoryStatus) DeepCopy() *GitHubRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinearConnectionConfig) DeepCopyInto(out *LinearConnectionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinearConnectionConfig.
func (in *LinearConnectionConfig) DeepCopy() *LinearConnectionConfig {
	if in == nil {
		return nil
	}
	out := new(LinearConnectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinearProject) DeepCopyInto(out *LinearProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinearProject.
func (in *LinearProject) DeepCopy() *LinearProject {
	if in == nil {
		return nil
	}
	out := new(LinearProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinearProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinearProjectList) DeepCopyInto(out *LinearProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LinearProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinearProjectList.
func (in *LinearProjectList) DeepCopy() *LinearProjectList {
	if in == nil {
		return nil
	}
	out := new(LinearProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinearProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinearProjectSpec) DeepCopyInto(out *LinearProjectSpec) {
	*out = *in
	out.PollInterval = in.PollInterval
	in.Defaults.DeepCopyInto(&out.Defaults)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinearProjectSpec.
func (in *LinearProjectSpec) DeepCopy() *LinearProjectSpec {
	if in == nil {
		return nil
	}
	out := new(LinearProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinearProjectStatus) DeepCopyInto(out *LinearProjectStatus) {
	*out = *in
	if in.LastPollTime != nil {
		in, out := &in.LastPollTime, &out.LastPollTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinearProjectStatus.
func (in *LinearProjectStatus) DeepCopy() *LinearProjectStatus {
	if in == nil {
		return nil
	}
	out := new(LinearProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinearProjectTriggerConfig) DeepCopyInto(out *LinearProjectTriggerConfig) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	out.PollInterval = in.PollInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinearProjectTriggerConfig.
func (in *LinearProjectTriggerConfig) DeepCopy() *LinearProjectTriggerConfig {
	if in == nil {
		return nil
	}
	out := new(LinearProjectTriggerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerAcceptedScope) DeepCopyInto(out *MaintainerAcceptedScope) {
	*out = *in
	if in.AcceptanceCriteria != nil {
		in, out := &in.AcceptanceCriteria, &out.AcceptanceCriteria
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerAcceptedScope.
func (in *MaintainerAcceptedScope) DeepCopy() *MaintainerAcceptedScope {
	if in == nil {
		return nil
	}
	out := new(MaintainerAcceptedScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerAuthenticatedHumanAnswer) DeepCopyInto(out *MaintainerAuthenticatedHumanAnswer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerAuthenticatedHumanAnswer.
func (in *MaintainerAuthenticatedHumanAnswer) DeepCopy() *MaintainerAuthenticatedHumanAnswer {
	if in == nil {
		return nil
	}
	out := new(MaintainerAuthenticatedHumanAnswer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerBreakdownCommand) DeepCopyInto(out *MaintainerBreakdownCommand) {
	*out = *in
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]MaintainerWorkItemReference, len(*in))
		copy(*out, *in)
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]MaintainerWorkItemReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerBreakdownCommand.
func (in *MaintainerBreakdownCommand) DeepCopy() *MaintainerBreakdownCommand {
	if in == nil {
		return nil
	}
	out := new(MaintainerBreakdownCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerDeliveryAttestation) DeepCopyInto(out *MaintainerDeliveryAttestation) {
	*out = *in
	out.Issuer = in.Issuer
	if in.RunSuccessRequestedRefs != nil {
		in, out := &in.RunSuccessRequestedRefs, &out.RunSuccessRequestedRefs
		*out = make([]MaintainerWorkItemReference, len(*in))
		copy(*out, *in)
	}
	if in.RunSuccessRequestedAt != nil {
		in, out := &in.RunSuccessRequestedAt, &out.RunSuccessRequestedAt
		*out = (*in).DeepCopy()
	}
	if in.IssueClosedAt != nil {
		in, out := &in.IssueClosedAt, &out.IssueClosedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	out.FinalizedByCommand = in.FinalizedByCommand
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerDeliveryAttestation.
func (in *MaintainerDeliveryAttestation) DeepCopy() *MaintainerDeliveryAttestation {
	if in == nil {
		return nil
	}
	out := new(MaintainerDeliveryAttestation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerDispatchReservation) DeepCopyInto(out *MaintainerDispatchReservation) {
	*out = *in
	out.CommandRef = in.CommandRef
	in.ReservedAt.DeepCopyInto(&out.ReservedAt)
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.AgentRunRef != nil {
		in, out := &in.AgentRunRef, &out.AgentRunRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerDispatchReservation.
func (in *MaintainerDispatchReservation) DeepCopy() *MaintainerDispatchReservation {
	if in == nil {
		return nil
	}
	out := new(MaintainerDispatchReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerDispatchWorkItemCommand) DeepCopyInto(out *MaintainerDispatchWorkItemCommand) {
	*out = *in
	if in.RequiredPullRequests != nil {
		in, out := &in.RequiredPullRequests, &out.RequiredPullRequests
		*out = make([]MaintainerRequiredPullRequestIntent, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerDispatchWorkItemCommand.
func (in *MaintainerDispatchWorkItemCommand) DeepCopy() *MaintainerDispatchWorkItemCommand {
	if in == nil {
		return nil
	}
	out := new(MaintainerDispatchWorkItemCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerFinalizeWorkItemCommand) DeepCopyInto(out *MaintainerFinalizeWorkItemCommand) {
	*out = *in
	if in.ImplementerRunNames != nil {
		in, out := &in.ImplementerRunNames, &out.ImplementerRunNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerFinalizeWorkItemCommand.
func (in *MaintainerFinalizeWorkItemCommand) DeepCopy() *MaintainerFinalizeWorkItemCommand {
	if in == nil {
		return nil
	}
	out := new(MaintainerFinalizeWorkItemCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerIssueObservation) DeepCopyInto(out *MaintainerIssueObservation) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.GitHubUpdatedAt.DeepCopyInto(&out.GitHubUpdatedAt)
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerIssueObservation.
func (in *MaintainerIssueObservation) DeepCopy() *MaintainerIssueObservation {
	if in == nil {
		return nil
	}
	out := new(MaintainerIssueObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerPendingDecision) DeepCopyInto(out *MaintainerPendingDecision) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.RequestedAt.DeepCopyInto(&out.RequestedAt)
	if in.RequestedByCommand != nil {
		in, out := &in.RequestedByCommand, &out.RequestedByCommand
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerPendingDecision.
func (in *MaintainerPendingDecision) DeepCopy() *MaintainerPendingDecision {
	if in == nil {
		return nil
	}
	out := new(MaintainerPendingDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerRequestDecisionCommand) DeepCopyInto(out *MaintainerRequestDecisionCommand) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerRequestDecisionCommand.
func (in *MaintainerRequestDecisionCommand) DeepCopy() *MaintainerRequestDecisionCommand {
	if in == nil {
		return nil
	}
	out := new(MaintainerRequestDecisionCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerRequestMergeCommand) DeepCopyInto(out *MaintainerRequestMergeCommand) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerRequestMergeCommand.
func (in *MaintainerRequestMergeCommand) DeepCopy() *MaintainerRequestMergeCommand {
	if in == nil {
		return nil
	}
	out := new(MaintainerRequestMergeCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerRequiredPullRequestIntent) DeepCopyInto(out *MaintainerRequiredPullRequestIntent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerRequiredPullRequestIntent.
func (in *MaintainerRequiredPullRequestIntent) DeepCopy() *MaintainerRequiredPullRequestIntent {
	if in == nil {
		return nil
	}
	out := new(MaintainerRequiredPullRequestIntent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerResolveDecisionCommand) DeepCopyInto(out *MaintainerResolveDecisionCommand) {
	*out = *in
	out.HumanAnswer = in.HumanAnswer
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerResolveDecisionCommand.
func (in *MaintainerResolveDecisionCommand) DeepCopy() *MaintainerResolveDecisionCommand {
	if in == nil {
		return nil
	}
	out := new(MaintainerResolveDecisionCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerResolvedDecision) DeepCopyInto(out *MaintainerResolvedDecision) {
	*out = *in
	in.ResolvedAt.DeepCopyInto(&out.ResolvedAt)
	out.ResolvedByCommand = in.ResolvedByCommand
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerResolvedDecision.
func (in *MaintainerResolvedDecision) DeepCopy() *MaintainerResolvedDecision {
	if in == nil {
		return nil
	}
	out := new(MaintainerResolvedDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerSpec) DeepCopyInto(out *MaintainerSpec) {
	*out = *in
	if in.ModeRef != nil {
		in, out := &in.ModeRef, &out.ModeRef
		*out = new(platformv1alpha1.ModeRef)
		**out = **in
	}
	if in.StandupInterval != nil {
		in, out := &in.StandupInterval, &out.StandupInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerSpec.
func (in *MaintainerSpec) DeepCopy() *MaintainerSpec {
	if in == nil {
		return nil
	}
	out := new(MaintainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerStatus) DeepCopyInto(out *MaintainerStatus) {
	*out = *in
	if in.LastWakeTime != nil {
		in, out := &in.LastWakeTime, &out.LastWakeTime
		*out = (*in).DeepCopy()
	}
	if in.LastReportTime != nil {
		in, out := &in.LastReportTime, &out.LastReportTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerStatus.
func (in *MaintainerStatus) DeepCopy() *MaintainerStatus {
	if in == nil {
		return nil
	}
	out := new(MaintainerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerTriageCommand) DeepCopyInto(out *MaintainerTriageCommand) {
	*out = *in
	in.AcceptedScope.DeepCopyInto(&out.AcceptedScope)
	if in.CloseReason != nil {
		in, out := &in.CloseReason, &out.CloseReason
		*out = new(MaintainerWorkItemCloseReason)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerTriageCommand.
func (in *MaintainerTriageCommand) DeepCopy() *MaintainerTriageCommand {
	if in == nil {
		return nil
	}
	out := new(MaintainerTriageCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerVerifiedPullRequestMerge) DeepCopyInto(out *MaintainerVerifiedPullRequestMerge) {
	*out = *in
	in.MergedAt.DeepCopyInto(&out.MergedAt)
	out.CommandRef = in.CommandRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerVerifiedPullRequestMerge.
func (in *MaintainerVerifiedPullRequestMerge) DeepCopy() *MaintainerVerifiedPullRequestMerge {
	if in == nil {
		return nil
	}
	out := new(MaintainerVerifiedPullRequestMerge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItem) DeepCopyInto(out *MaintainerWorkItem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItem.
func (in *MaintainerWorkItem) DeepCopy() *MaintainerWorkItem {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintainerWorkItem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemAgentRunProjection) DeepCopyInto(out *MaintainerWorkItemAgentRunProjection) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemAgentRunProjection.
func (in *MaintainerWorkItemAgentRunProjection) DeepCopy() *MaintainerWorkItemAgentRunProjection {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemAgentRunProjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemChildProjection) DeepCopyInto(out *MaintainerWorkItemChildProjection) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemChildProjection.
func (in *MaintainerWorkItemChildProjection) DeepCopy() *MaintainerWorkItemChildProjection {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemChildProjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemCommand) DeepCopyInto(out *MaintainerWorkItemCommand) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemCommand.
func (in *MaintainerWorkItemCommand) DeepCopy() *MaintainerWorkItemCommand {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintainerWorkItemCommand) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemCommandIssuer) DeepCopyInto(out *MaintainerWorkItemCommandIssuer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemCommandIssuer.
func (in *MaintainerWorkItemCommandIssuer) DeepCopy() *MaintainerWorkItemCommandIssuer {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemCommandIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemCommandList) DeepCopyInto(out *MaintainerWorkItemCommandList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaintainerWorkItemCommand, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemCommandList.
func (in *MaintainerWorkItemCommandList) DeepCopy() *MaintainerWorkItemCommandList {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemCommandList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintainerWorkItemCommandList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemCommandObservation) DeepCopyInto(out *MaintainerWorkItemCommandObservation) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemCommandObservation.
func (in *MaintainerWorkItemCommandObservation) DeepCopy() *MaintainerWorkItemCommandObservation {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemCommandObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemCommandPreconditions) DeepCopyInto(out *MaintainerWorkItemCommandPreconditions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemCommandPreconditions.
func (in *MaintainerWorkItemCommandPreconditions) DeepCopy() *MaintainerWorkItemCommandPreconditions {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemCommandPreconditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemCommandResult) DeepCopyInto(out *MaintainerWorkItemCommandResult) {
	*out = *in
	out.WorkItemRef = in.WorkItemRef
	if in.ChildRefs != nil {
		in, out := &in.ChildRefs, &out.ChildRefs
		*out = make([]MaintainerWorkItemReference, len(*in))
		copy(*out, *in)
	}
	if in.DispatchReservation != nil {
		in, out := &in.DispatchReservation, &out.DispatchReservation
		*out = new(MaintainerDispatchReservation)
		(*in).DeepCopyInto(*out)
	}
	if in.AgentRunRef != nil {
		in, out := &in.AgentRunRef, &out.AgentRunRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.MergeAttemptedAt != nil {
		in, out := &in.MergeAttemptedAt, &out.MergeAttemptedAt
		*out = (*in).DeepCopy()
	}
	if in.VerifiedMerge != nil {
		in, out := &in.VerifiedMerge, &out.VerifiedMerge
		*out = new(MaintainerVerifiedPullRequestMerge)
		(*in).DeepCopyInto(*out)
	}
	if in.DeliveryAttestation != nil {
		in, out := &in.DeliveryAttestation, &out.DeliveryAttestation
		*out = new(MaintainerDeliveryAttestation)
		(*in).DeepCopyInto(*out)
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemCommandResult.
func (in *MaintainerWorkItemCommandResult) DeepCopy() *MaintainerWorkItemCommandResult {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemCommandResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemCommandSpec) DeepCopyInto(out *MaintainerWorkItemCommandSpec) {
	*out = *in
	out.RepositoryRef = in.RepositoryRef
	out.Issuer = in.Issuer
	out.Preconditions = in.Preconditions
	if in.Triage != nil {
		in, out := &in.Triage, &out.Triage
		*out = new(MaintainerTriageCommand)
		(*in).DeepCopyInto(*out)
	}
	if in.Breakdown != nil {
		in, out := &in.Breakdown, &out.Breakdown
		*out = new(MaintainerBreakdownCommand)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestDecision != nil {
		in, out := &in.RequestDecision, &out.RequestDecision
		*out = new(MaintainerRequestDecisionCommand)
		(*in).DeepCopyInto(*out)
	}
	if in.ResolveDecision != nil {
		in, out := &in.ResolveDecision, &out.ResolveDecision
		*out = new(MaintainerResolveDecisionCommand)
		**out = **in
	}
	if in.Dispatch != nil {
		in, out := &in.Dispatch, &out.Dispatch
		*out = new(MaintainerDispatchWorkItemCommand)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestMerge != nil {
		in, out := &in.RequestMerge, &out.RequestMerge
		*out = new(MaintainerRequestMergeCommand)
		**out = **in
	}
	if in.Finalize != nil {
		in, out := &in.Finalize, &out.Finalize
		*out = new(MaintainerFinalizeWorkItemCommand)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemCommandSpec.
func (in *MaintainerWorkItemCommandSpec) DeepCopy() *MaintainerWorkItemCommandSpec {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemCommandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemCommandStatus) DeepCopyInto(out *MaintainerWorkItemCommandStatus) {
	*out = *in
	if in.Result != nil {
		in, out := &in.Result, &out.Result
		*out = new(MaintainerWorkItemCommandResult)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemCommandStatus.
func (in *MaintainerWorkItemCommandStatus) DeepCopy() *MaintainerWorkItemCommandStatus {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemCommandStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemDependencyProjection) DeepCopyInto(out *MaintainerWorkItemDependencyProjection) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemDependencyProjection.
func (in *MaintainerWorkItemDependencyProjection) DeepCopy() *MaintainerWorkItemDependencyProjection {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemDependencyProjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemList) DeepCopyInto(out *MaintainerWorkItemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaintainerWorkItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemList.
func (in *MaintainerWorkItemList) DeepCopy() *MaintainerWorkItemList {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintainerWorkItemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemPullRequestProjection) DeepCopyInto(out *MaintainerWorkItemPullRequestProjection) {
	*out = *in
	if in.MonitorRef != nil {
		in, out := &in.MonitorRef, &out.MonitorRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.MergedAt != nil {
		in, out := &in.MergedAt, &out.MergedAt
		*out = (*in).DeepCopy()
	}
	if in.Mergeable != nil {
		in, out := &in.Mergeable, &out.Mergeable
		*out = new(bool)
		**out = **in
	}
	if in.HeadObservedAt != nil {
		in, out := &in.HeadObservedAt, &out.HeadObservedAt
		*out = (*in).DeepCopy()
	}
	if in.ReviewObservedAt != nil {
		in, out := &in.ReviewObservedAt, &out.ReviewObservedAt
		*out = (*in).DeepCopy()
	}
	if in.ChecksObservedAt != nil {
		in, out := &in.ChecksObservedAt, &out.ChecksObservedAt
		*out = (*in).DeepCopy()
	}
	if in.StatusesObservedAt != nil {
		in, out := &in.StatusesObservedAt, &out.StatusesObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemPullRequestProjection.
func (in *MaintainerWorkItemPullRequestProjection) DeepCopy() *MaintainerWorkItemPullRequestProjection {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemPullRequestProjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemReadiness) DeepCopyInto(out *MaintainerWorkItemReadiness) {
	*out = *in
	if in.UnmetRequirements != nil {
		in, out := &in.UnmetRequirements, &out.UnmetRequirements
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemReadiness.
func (in *MaintainerWorkItemReadiness) DeepCopy() *MaintainerWorkItemReadiness {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemReadiness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemReference) DeepCopyInto(out *MaintainerWorkItemReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemReference.
func (in *MaintainerWorkItemReference) DeepCopy() *MaintainerWorkItemReference {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemSpec) DeepCopyInto(out *MaintainerWorkItemSpec) {
	*out = *in
	out.RepositoryRef = in.RepositoryRef
	if in.AcceptedScope != nil {
		in, out := &in.AcceptedScope, &out.AcceptedScope
		*out = new(MaintainerAcceptedScope)
		(*in).DeepCopyInto(*out)
	}
	if in.CloseReason != nil {
		in, out := &in.CloseReason, &out.CloseReason
		*out = new(MaintainerWorkItemCloseReason)
		**out = **in
	}
	if in.TriagedByCommand != nil {
		in, out := &in.TriagedByCommand, &out.TriagedByCommand
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]MaintainerWorkItemReference, len(*in))
		copy(*out, *in)
	}
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]MaintainerWorkItemReference, len(*in))
		copy(*out, *in)
	}
	if in.RequiredPullRequests != nil {
		in, out := &in.RequiredPullRequests, &out.RequiredPullRequests
		*out = make([]MaintainerRequiredPullRequestIntent, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemSpec.
func (in *MaintainerWorkItemSpec) DeepCopy() *MaintainerWorkItemSpec {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerWorkItemStatus) DeepCopyInto(out *MaintainerWorkItemStatus) {
	*out = *in
	if in.IssueObservation != nil {
		in, out := &in.IssueObservation, &out.IssueObservation
		*out = new(MaintainerIssueObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]MaintainerWorkItemChildProjection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]MaintainerWorkItemDependencyProjection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AgentRuns != nil {
		in, out := &in.AgentRuns, &out.AgentRuns
		*out = make([]MaintainerWorkItemAgentRunProjection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PullRequests != nil {
		in, out := &in.PullRequests, &out.PullRequests
		*out = make([]MaintainerWorkItemPullRequestProjection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VerifiedMerges != nil {
		in, out := &in.VerifiedMerges, &out.VerifiedMerges
		*out = make([]MaintainerVerifiedPullRequestMerge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeliveryAttestation != nil {
		in, out := &in.DeliveryAttestation, &out.DeliveryAttestation
		*out = new(MaintainerDeliveryAttestation)
		(*in).DeepCopyInto(*out)
	}
	if in.LatestCommand != nil {
		in, out := &in.LatestCommand, &out.LatestCommand
		*out = new(MaintainerWorkItemCommandObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Readiness != nil {
		in, out := &in.Readiness, &out.Readiness
		*out = new(MaintainerWorkItemReadiness)
		(*in).DeepCopyInto(*out)
	}
	if in.PendingDecision != nil {
		in, out := &in.PendingDecision, &out.PendingDecision
		*out = new(MaintainerPendingDecision)
		(*in).DeepCopyInto(*out)
	}
	if in.ResolvedDecision != nil {
		in, out := &in.ResolvedDecision, &out.ResolvedDecision
		*out = new(MaintainerResolvedDecision)
		(*in).DeepCopyInto(*out)
	}
	if in.DispatchReservation != nil {
		in, out := &in.DispatchReservation, &out.DispatchReservation
		*out = new(MaintainerDispatchReservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerWorkItemStatus.
func (in *MaintainerWorkItemStatus) DeepCopy() *MaintainerWorkItemStatus {
	if in == nil {
		return nil
	}
	out := new(MaintainerWorkItemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectList.
func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectReviewLoopSpec) DeepCopyInto(out *ProjectReviewLoopSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectReviewLoopSpec.
func (in *ProjectReviewLoopSpec) DeepCopy() *ProjectReviewLoopSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectReviewLoopSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(TriggerAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.ReviewLoop != nil {
		in, out := &in.ReviewLoop, &out.ReviewLoop
		*out = new(ProjectReviewLoopSpec)
		**out = **in
	}
	in.Defaults.DeepCopyInto(&out.Defaults)
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]ProjectTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]ProjectTriggerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectStatus.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectTrigger) DeepCopyInto(out *ProjectTrigger) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(GitHubProjectTriggerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackProjectTriggerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Cron != nil {
		in, out := &in.Cron, &out.Cron
		*out = new(CronProjectTriggerConfig)
		**out = **in
	}
	if in.Linear != nil {
		in, out := &in.Linear, &out.Linear
		*out = new(LinearProjectTriggerConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectTrigger.
func (in *ProjectTrigger) DeepCopy() *ProjectTrigger {
	if in == nil {
		return nil
	}
	out := new(ProjectTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectTriggerStatus) DeepCopyInto(out *ProjectTriggerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastActivityTime != nil {
		in, out := &in.LastActivityTime, &out.LastActivityTime
		*out = (*in).DeepCopy()
	}
	if in.NextActivityTime != nil {
		in, out := &in.NextActivityTime, &out.NextActivityTime
		*out = (*in).DeepCopy()
	}
	if in.Maintainer != nil {
		in, out := &in.Maintainer, &out.Maintainer
		*out = new(MaintainerStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectTriggerStatus.
func (in *ProjectTriggerStatus) DeepCopy() *ProjectTriggerStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectTriggerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestMonitor) DeepCopyInto(out *PullRequestMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestMonitor.
func (in *PullRequestMonitor) DeepCopy() *PullRequestMonitor {
	if in == nil {
		return nil
	}
	out := new(PullRequestMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PullRequestMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestMonitorETags) DeepCopyInto(out *PullRequestMonitorETags) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestMonitorETags.
func (in *PullRequestMonitorETags) DeepCopy() *PullRequestMonitorETags {
	if in == nil {
		return nil
	}
	out := new(PullRequestMonitorETags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestMonitorHeadRollup) DeepCopyInto(out *PullRequestMonitorHeadRollup) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestMonitorHeadRollup.
func (in *PullRequestMonitorHeadRollup) DeepCopy() *PullRequestMonitorHeadRollup {
	if in == nil {
		return nil
	}
	out := new(PullRequestMonitorHeadRollup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestMonitorList) DeepCopyInto(out *PullRequestMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PullRequestMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestMonitorList.
func (in *PullRequestMonitorList) DeepCopy() *PullRequestMonitorList {
	if in == nil {
		return nil
	}
	out := new(PullRequestMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PullRequestMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestMonitorSpec) DeepCopyInto(out *PullRequestMonitorSpec) {
	*out = *in
	out.ImplementerRef = in.ImplementerRef
	if in.GitHubRepositoryRef != nil {
		in, out := &in.GitHubRepositoryRef, &out.GitHubRepositoryRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	in.DiscoveredAt.DeepCopyInto(&out.DiscoveredAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestMonitorSpec.
func (in *PullRequestMonitorSpec) DeepCopy() *PullRequestMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(PullRequestMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestMonitorStatus) DeepCopyInto(out *PullRequestMonitorStatus) {
	*out = *in
	in.MergedAt.DeepCopyInto(&out.MergedAt)
	in.PullObservedAt.DeepCopyInto(&out.PullObservedAt)
	in.ReviewsObservedAt.DeepCopyInto(&out.ReviewsObservedAt)
	in.CommentsObservedAt.DeepCopyInto(&out.CommentsObservedAt)
	in.Checks.DeepCopyInto(&out.Checks)
	in.Statuses.DeepCopyInto(&out.Statuses)
	if in.LastPollTime != nil {
		in, out := &in.LastPollTime, &out.LastPollTime
		*out = (*in).DeepCopy()
	}
	if in.LastReviewCursor != nil {
		in, out := &in.LastReviewCursor, &out.LastReviewCursor
		*out = new(GitHubObjectCursor)
		(*in).DeepCopyInto(*out)
	}
	if in.LastIssueCommentCursor != nil {
		in, out := &in.LastIssueCommentCursor, &out.LastIssueCommentCursor
		*out = new(GitHubObjectCursor)
		(*in).DeepCopyInto(*out)
	}
	out.ETags = in.ETags
	if in.RetryAfter != nil {
		in, out := &in.RetryAfter, &out.RetryAfter
		*out = (*in).DeepCopy()
	}
	if in.RateLimitReset != nil {
		in, out := &in.RateLimitReset, &out.RateLimitReset
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestMonitorStatus.
func (in *PullRequestMonitorStatus) DeepCopy() *PullRequestMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(PullRequestMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewLoopSpec) DeepCopyInto(out *ReviewLoopSpec) {
	*out = *in
	if in.ReviewerModeRef != nil {
		in, out := &in.ReviewerModeRef, &out.ReviewerModeRef
		*out = new(platformv1alpha1.ModeRef)
		**out = **in
	}
	if in.ReviewerDefaults != nil {
		in, out := &in.ReviewerDefaults, &out.ReviewerDefaults
		*out = new(AgentRunDefaults)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewLoopSpec.
func (in *ReviewLoopSpec) DeepCopy() *ReviewLoopSpec {
	if in == nil {
		return nil
	}
	out := new(ReviewLoopSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackAgent) DeepCopyInto(out *SlackAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackAgent.
func (in *SlackAgent) DeepCopy() *SlackAgent {
	if in == nil {
		return nil
	}
	out := new(SlackAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlackAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackAgentList) DeepCopyInto(out *SlackAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlackAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackAgentList.
func (in *SlackAgentList) DeepCopy() *SlackAgentList {
	if in == nil {
		return nil
	}
	out := new(SlackAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlackAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackAgentSpec) DeepCopyInto(out *SlackAgentSpec) {
	*out = *in
	if in.WorkspaceRef != nil {
		in, out := &in.WorkspaceRef, &out.WorkspaceRef
		*out = new(SlackWorkspaceRef)
		**out = **in
	}
	if in.Commanders != nil {
		in, out := &in.Commanders, &out.Commanders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SessionIdleMinutes != nil {
		in, out := &in.SessionIdleMinutes, &out.SessionIdleMinutes
		*out = new(int32)
		**out = **in
	}
	if in.AppHome != nil {
		in, out := &in.AppHome, &out.AppHome
		*out = new(SlackAppHomeSpec)
		**out = **in
	}
	in.Defaults.DeepCopyInto(&out.Defaults)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackAgentSpec.
func (in *SlackAgentSpec) DeepCopy() *SlackAgentSpec {
	if in == nil {
		return nil
	}
	out := new(SlackAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackAgentStatus) DeepCopyInto(out *SlackAgentStatus) {
	*out = *in
	if in.LastEventTime != nil {
		in, out := &in.LastEventTime, &out.LastEventTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackAgentStatus.
func (in *SlackAgentStatus) DeepCopy() *SlackAgentStatus {
	if in == nil {
		return nil
	}
	out := new(SlackAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackAppHomeSpec) DeepCopyInto(out *SlackAppHomeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackAppHomeSpec.
func (in *SlackAppHomeSpec) DeepCopy() *SlackAppHomeSpec {
	if in == nil {
		return nil
	}
	out := new(SlackAppHomeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackConnectionConfig) DeepCopyInto(out *SlackConnectionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackConnectionConfig.
func (in *SlackConnectionConfig) DeepCopy() *SlackConnectionConfig {
	if in == nil {
		return nil
	}
	out := new(SlackConnectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackProjectTriggerConfig) DeepCopyInto(out *SlackProjectTriggerConfig) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	if in.Commanders != nil {
		in, out := &in.Commanders, &out.Commanders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SessionIdleMinutes != nil {
		in, out := &in.SessionIdleMinutes, &out.SessionIdleMinutes
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackProjectTriggerConfig.
func (in *SlackProjectTriggerConfig) DeepCopy() *SlackProjectTriggerConfig {
	if in == nil {
		return nil
	}
	out := new(SlackProjectTriggerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackWorkspace) DeepCopyInto(out *SlackWorkspace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackWorkspace.
func (in *SlackWorkspace) DeepCopy() *SlackWorkspace {
	if in == nil {
		return nil
	}
	out := new(SlackWorkspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlackWorkspace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackWorkspaceList) DeepCopyInto(out *SlackWorkspaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlackWorkspace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackWorkspaceList.
func (in *SlackWorkspaceList) DeepCopy() *SlackWorkspaceList {
	if in == nil {
		return nil
	}
	out := new(SlackWorkspaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlackWorkspaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackWorkspaceRef) DeepCopyInto(out *SlackWorkspaceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackWorkspaceRef.
func (in *SlackWorkspaceRef) DeepCopy() *SlackWorkspaceRef {
	if in == nil {
		return nil
	}
	out := new(SlackWorkspaceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackWorkspaceSpec) DeepCopyInto(out *SlackWorkspaceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackWorkspaceSpec.
func (in *SlackWorkspaceSpec) DeepCopy() *SlackWorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(SlackWorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackWorkspaceStatus) DeepCopyInto(out *SlackWorkspaceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackWorkspaceStatus.
func (in *SlackWorkspaceStatus) DeepCopy() *SlackWorkspaceStatus {
	if in == nil {
		return nil
	}
	out := new(SlackWorkspaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerAuth) DeepCopyInto(out *TriggerAuth) {
	*out = *in
	if in.AllowedUsers != nil {
		in, out := &in.AllowedUsers, &out.AllowedUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DenyUsers != nil {
		in, out := &in.DenyUsers, &out.DenyUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerAuth.
func (in *TriggerAuth) DeepCopy() *TriggerAuth {
	if in == nil {
		return nil
	}
	out := new(TriggerAuth)
	in.DeepCopyInto(out)
	return out
}
