// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getActivityEvents = `-- name: GetActivityEvents :many
SELECT id, session_id, event_type, summary, detail, created_at FROM activity_events
WHERE session_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) GetActivityEvents(ctx context.Context, sessionID uuid.UUID) ([]ActivityEvent, error) {
	rows, err := q.db.Query(ctx, getActivityEvents, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityEvent{}
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EventType,
			&i.Summary,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentActivityEvents = `-- name: GetRecentActivityEvents :many
SELECT id, session_id, event_type, summary, detail, created_at FROM activity_events
WHERE session_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type GetRecentActivityEventsParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) GetRecentActivityEvents(ctx context.Context, arg GetRecentActivityEventsParams) ([]ActivityEvent, error) {
	rows, err := q.db.Query(ctx, getRecentActivityEvents, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityEvent{}
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EventType,
			&i.Summary,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeActivityEvent = `-- name: WriteActivityEvent :one
INSERT INTO activity_events (session_id, event_type, summary, detail)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, event_type, summary, detail, created_at
`

type WriteActivityEventParams struct {
	SessionID uuid.UUID       `json:"session_id"`
	EventType string          `json:"event_type"`
	Summary   string          `json:"summary"`
	Detail    json.RawMessage `json:"detail"`
}

func (q *Queries) WriteActivityEvent(ctx context.Context, arg WriteActivityEventParams) (ActivityEvent, error) {
	row := q.db.QueryRow(ctx, writeActivityEvent,
		arg.SessionID,
		arg.EventType,
		arg.Summary,
		arg.Detail,
	)
	var i ActivityEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.EventType,
		&i.Summary,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}
