// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getArtifact = `-- name: GetArtifact :one
SELECT id, session_id, kind, content, s3_url, content_hash, metadata, created_at, updated_at FROM agent_artifacts
WHERE session_id = $1 AND kind = $2
`

type GetArtifactParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Kind      string    `json:"kind"`
}

func (q *Queries) GetArtifact(ctx context.Context, arg GetArtifactParams) (AgentArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, arg.SessionID, arg.Kind)
	var i AgentArtifact
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Kind,
		&i.Content,
		&i.S3Url,
		&i.ContentHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifacts = `-- name: GetArtifacts :many
SELECT id, session_id, kind, content, s3_url, content_hash, metadata, created_at, updated_at FROM agent_artifacts
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetArtifacts(ctx context.Context, sessionID uuid.UUID) ([]AgentArtifact, error) {
	rows, err := q.db.Query(ctx, getArtifacts, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentArtifact{}
	for rows.Next() {
		var i AgentArtifact
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Kind,
			&i.Content,
			&i.S3Url,
			&i.ContentHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArtifact = `-- name: UpsertArtifact :one
INSERT INTO agent_artifacts (session_id, kind, content, s3_url, content_hash, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (session_id, kind) DO UPDATE
SET content = EXCLUDED.content,
    s3_url = EXCLUDED.s3_url,
    content_hash = EXCLUDED.content_hash,
    metadata = EXCLUDED.metadata
RETURNING id, session_id, kind, content, s3_url, content_hash, metadata, created_at, updated_at
`

type UpsertArtifactParams struct {
	SessionID   uuid.UUID       `json:"session_id"`
	Kind        string          `json:"kind"`
	Content     string          `json:"content"`
	S3Url       string          `json:"s3_url"`
	ContentHash string          `json:"content_hash"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (AgentArtifact, error) {
	row := q.db.QueryRow(ctx, upsertArtifact,
		arg.SessionID,
		arg.Kind,
		arg.Content,
		arg.S3Url,
		arg.ContentHash,
		arg.Metadata,
	)
	var i AgentArtifact
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Kind,
		&i.Content,
		&i.S3Url,
		&i.ContentHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
