// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collaboration.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (user_id, type, title, body, resource_type, resource_id, resource_namespace, actor_id, actor_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateNotificationParams struct {
	UserID            string `json:"user_id"`
	Type              string `json:"type"`
	Title             string `json:"title"`
	Body              string `json:"body"`
	ResourceType      string `json:"resource_type"`
	ResourceID        string `json:"resource_id"`
	ResourceNamespace string `json:"resource_namespace"`
	ActorID           string `json:"actor_id"`
	ActorName         string `json:"actor_name"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceNamespace,
		arg.ActorID,
		arg.ActorName,
	)
	return err
}

const getResourceOwner = `-- name: GetResourceOwner :one
SELECT id, resource_type, resource_id, resource_namespace, owner_id, created_at FROM resource_ownership
WHERE resource_type = $1 AND resource_id = $2 AND resource_namespace = $3
`

type GetResourceOwnerParams struct {
	ResourceType      string `json:"resource_type"`
	ResourceID        string `json:"resource_id"`
	ResourceNamespace string `json:"resource_namespace"`
}

func (q *Queries) GetResourceOwner(ctx context.Context, arg GetResourceOwnerParams) (ResourceOwnership, error) {
	row := q.db.QueryRow(ctx, getResourceOwner, arg.ResourceType, arg.ResourceID, arg.ResourceNamespace)
	var i ResourceOwnership
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceNamespace,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getSharePermission = `-- name: GetSharePermission :one
SELECT id, resource_type, resource_id, resource_namespace, shared_with_user_id, shared_by_user_id, permission, created_at, updated_at FROM resource_shares
WHERE resource_type = $1 AND resource_id = $2 AND resource_namespace = $3 AND shared_with_user_id = $4
`

type GetSharePermissionParams struct {
	ResourceType      string `json:"resource_type"`
	ResourceID        string `json:"resource_id"`
	ResourceNamespace string `json:"resource_namespace"`
	SharedWithUserID  string `json:"shared_with_user_id"`
}

func (q *Queries) GetSharePermission(ctx context.Context, arg GetSharePermissionParams) (ResourceShare, error) {
	row := q.db.QueryRow(ctx, getSharePermission,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceNamespace,
		arg.SharedWithUserID,
	)
	var i ResourceShare
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceNamespace,
		&i.SharedWithUserID,
		&i.SharedByUserID,
		&i.Permission,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT count(*)::int FROM notifications WHERE user_id = $1 AND read = false
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, getUnreadNotificationCount, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, title, body, resource_type, resource_id, resource_namespace, actor_id, actor_name, read, created_at FROM notifications
WHERE user_id = $1 AND ($2::boolean = false OR read = false)
ORDER BY created_at DESC
LIMIT $3
`

type ListNotificationsParams struct {
	UserID  string `json:"user_id"`
	Column2 bool   `json:"column_2"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceNamespace,
			&i.ActorID,
			&i.ActorName,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedResources = `-- name: ListOwnedResources :many
SELECT id, resource_type, resource_id, resource_namespace, owner_id, created_at FROM resource_ownership
WHERE owner_id = $1 AND resource_type = $2
ORDER BY created_at DESC
`

type ListOwnedResourcesParams struct {
	OwnerID      string `json:"owner_id"`
	ResourceType string `json:"resource_type"`
}

func (q *Queries) ListOwnedResources(ctx context.Context, arg ListOwnedResourcesParams) ([]ResourceOwnership, error) {
	rows, err := q.db.Query(ctx, listOwnedResources, arg.OwnerID, arg.ResourceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceOwnership{}
	for rows.Next() {
		var i ResourceOwnership
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceNamespace,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedWithMe = `-- name: ListSharedWithMe :many
SELECT id, resource_type, resource_id, resource_namespace, shared_with_user_id, shared_by_user_id, permission, created_at, updated_at FROM resource_shares
WHERE shared_with_user_id = $1 AND ($2::text = '' OR resource_type = $2)
ORDER BY created_at DESC
`

type ListSharedWithMeParams struct {
	SharedWithUserID string `json:"shared_with_user_id"`
	Column2          string `json:"column_2"`
}

func (q *Queries) ListSharedWithMe(ctx context.Context, arg ListSharedWithMeParams) ([]ResourceShare, error) {
	rows, err := q.db.Query(ctx, listSharedWithMe, arg.SharedWithUserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceShare{}
	for rows.Next() {
		var i ResourceShare
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceNamespace,
			&i.SharedWithUserID,
			&i.SharedByUserID,
			&i.Permission,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharesForResource = `-- name: ListSharesForResource :many
SELECT id, resource_type, resource_id, resource_namespace, shared_with_user_id, shared_by_user_id, permission, created_at, updated_at FROM resource_shares
WHERE resource_type = $1 AND resource_id = $2 AND resource_namespace = $3
ORDER BY created_at DESC
`

type ListSharesForResourceParams struct {
	ResourceType      string `json:"resource_type"`
	ResourceID        string `json:"resource_id"`
	ResourceNamespace string `json:"resource_namespace"`
}

func (q *Queries) ListSharesForResource(ctx context.Context, arg ListSharesForResourceParams) ([]ResourceShare, error) {
	rows, err := q.db.Query(ctx, listSharesForResource, arg.ResourceType, arg.ResourceID, arg.ResourceNamespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceShare{}
	for rows.Next() {
		var i ResourceShare
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceNamespace,
			&i.SharedWithUserID,
			&i.SharedByUserID,
			&i.Permission,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read = true WHERE user_id = $1 AND read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read = true WHERE id = $1
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationRead, id)
	return err
}

const revokeShare = `-- name: RevokeShare :exec
DELETE FROM resource_shares WHERE id = $1
`

func (q *Queries) RevokeShare(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeShare, id)
	return err
}

const setResourceOwner = `-- name: SetResourceOwner :exec
INSERT INTO resource_ownership (resource_type, resource_id, resource_namespace, owner_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (resource_type, resource_id, resource_namespace) DO UPDATE SET
    owner_id = EXCLUDED.owner_id
`

type SetResourceOwnerParams struct {
	ResourceType      string `json:"resource_type"`
	ResourceID        string `json:"resource_id"`
	ResourceNamespace string `json:"resource_namespace"`
	OwnerID           string `json:"owner_id"`
}

func (q *Queries) SetResourceOwner(ctx context.Context, arg SetResourceOwnerParams) error {
	_, err := q.db.Exec(ctx, setResourceOwner,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceNamespace,
		arg.OwnerID,
	)
	return err
}

const shareResource = `-- name: ShareResource :one
INSERT INTO resource_shares (resource_type, resource_id, resource_namespace, shared_with_user_id, shared_by_user_id, permission)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (resource_type, resource_id, resource_namespace, shared_with_user_id) DO UPDATE SET
    permission = EXCLUDED.permission,
    updated_at = now()
RETURNING id, resource_type, resource_id, resource_namespace, shared_with_user_id, shared_by_user_id, permission, created_at, updated_at
`

type ShareResourceParams struct {
	ResourceType      string `json:"resource_type"`
	ResourceID        string `json:"resource_id"`
	ResourceNamespace string `json:"resource_namespace"`
	SharedWithUserID  string `json:"shared_with_user_id"`
	SharedByUserID    string `json:"shared_by_user_id"`
	Permission        string `json:"permission"`
}

func (q *Queries) ShareResource(ctx context.Context, arg ShareResourceParams) (ResourceShare, error) {
	row := q.db.QueryRow(ctx, shareResource,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceNamespace,
		arg.SharedWithUserID,
		arg.SharedByUserID,
		arg.Permission,
	)
	var i ResourceShare
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceNamespace,
		&i.SharedWithUserID,
		&i.SharedByUserID,
		&i.Permission,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSharePermission = `-- name: UpdateSharePermission :exec
UPDATE resource_shares SET permission = $2, updated_at = now() WHERE id = $1
`

type UpdateSharePermissionParams struct {
	ID         uuid.UUID `json:"id"`
	Permission string    `json:"permission"`
}

func (q *Queries) UpdateSharePermission(ctx context.Context, arg UpdateSharePermissionParams) error {
	_, err := q.db.Exec(ctx, updateSharePermission, arg.ID, arg.Permission)
	return err
}
