// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const appendMessage = `-- name: AppendMessage :one
INSERT INTO conversation_messages (session_id, role, content, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, role, content, metadata, created_at, delivery_state, claimed_at, delivery_sequence, claim_token
`

type AppendMessageParams struct {
	SessionID uuid.UUID       `json:"session_id"`
	Role      string          `json:"role"`
	Content   string          `json:"content"`
	Metadata  json.RawMessage `json:"metadata"`
}

func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (ConversationMessage, error) {
	row := q.db.QueryRow(ctx, appendMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.Metadata,
	)
	var i ConversationMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
		&i.DeliveryState,
		&i.ClaimedAt,
		&i.DeliverySequence,
		&i.ClaimToken,
	)
	return i, err
}

const getLatestUserMessage = `-- name: GetLatestUserMessage :one
SELECT id, session_id, role, content, metadata, created_at, delivery_state, claimed_at, delivery_sequence, claim_token FROM conversation_messages
WHERE session_id = $1 AND role = 'user'
  AND NOT (COALESCE(metadata, '{}'::jsonb) ? 'overseer_held')
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestUserMessage(ctx context.Context, sessionID uuid.UUID) (ConversationMessage, error) {
	row := q.db.QueryRow(ctx, getLatestUserMessage, sessionID)
	var i ConversationMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
		&i.DeliveryState,
		&i.ClaimedAt,
		&i.DeliverySequence,
		&i.ClaimToken,
	)
	return i, err
}

const getMessageCount = `-- name: GetMessageCount :one
SELECT count(*) FROM conversation_messages
WHERE session_id = $1
  AND NOT (COALESCE(metadata, '{}'::jsonb) ? 'overseer_held')
`

func (q *Queries) GetMessageCount(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getMessageCount, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMessages = `-- name: GetMessages :many
SELECT id, session_id, role, content, metadata, created_at, delivery_state, claimed_at, delivery_sequence, claim_token FROM conversation_messages
WHERE session_id = $1
  AND NOT (COALESCE(metadata, '{}'::jsonb) ? 'overseer_held')
  AND NOT (role = 'user' AND COALESCE(metadata, '{}'::jsonb) ? 'cancelled_at_unix')
ORDER BY id ASC
`

func (q *Queries) GetMessages(ctx context.Context, sessionID uuid.UUID) ([]ConversationMessage, error) {
	rows, err := q.db.Query(ctx, getMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationMessage{}
	for rows.Next() {
		var i ConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
			&i.DeliveryState,
			&i.ClaimedAt,
			&i.DeliverySequence,
			&i.ClaimToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesIncludingCancelled = `-- name: GetMessagesIncludingCancelled :many
SELECT id, session_id, role, content, metadata, created_at, delivery_state, claimed_at, delivery_sequence, claim_token FROM conversation_messages
WHERE session_id = $1
  AND NOT (COALESCE(metadata, '{}'::jsonb) ? 'overseer_held')
ORDER BY id ASC
`

func (q *Queries) GetMessagesIncludingCancelled(ctx context.Context, sessionID uuid.UUID) ([]ConversationMessage, error) {
	rows, err := q.db.Query(ctx, getMessagesIncludingCancelled, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationMessage{}
	for rows.Next() {
		var i ConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
			&i.DeliveryState,
			&i.ClaimedAt,
			&i.DeliverySequence,
			&i.ClaimToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesSince = `-- name: GetMessagesSince :many
SELECT id, session_id, role, content, metadata, created_at, delivery_state, claimed_at, delivery_sequence, claim_token FROM conversation_messages
WHERE session_id = $1 AND id > $2
  AND NOT (COALESCE(metadata, '{}'::jsonb) ? 'overseer_held')
  AND NOT (role = 'user' AND COALESCE(metadata, '{}'::jsonb) ? 'cancelled_at_unix')
ORDER BY id ASC
`

type GetMessagesSinceParams struct {
	SessionID uuid.UUID `json:"session_id"`
	ID        int64     `json:"id"`
}

func (q *Queries) GetMessagesSince(ctx context.Context, arg GetMessagesSinceParams) ([]ConversationMessage, error) {
	rows, err := q.db.Query(ctx, getMessagesSince, arg.SessionID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationMessage{}
	for rows.Next() {
		var i ConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
			&i.DeliveryState,
			&i.ClaimedAt,
			&i.DeliverySequence,
			&i.ClaimToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollNewUserMessages = `-- name: PollNewUserMessages :many
SELECT candidate.id, candidate.session_id, candidate.role, candidate.content, candidate.metadata, candidate.created_at, candidate.delivery_state, candidate.claimed_at, candidate.delivery_sequence, candidate.claim_token FROM conversation_messages AS candidate
WHERE candidate.session_id = $1 AND candidate.role = 'user'
  AND candidate.delivery_state = 'pending'
  AND NOT (COALESCE(candidate.metadata, '{}'::jsonb) ? 'cancelled_at_unix')
  -- Pending state is authoritative. Exact stopped prompts are completed when
  -- interrupted; a scalar cursor must never hide a different pending hole.
  AND $2 >= 0
  AND NOT (COALESCE(candidate.metadata, '{}'::jsonb) ? 'overseer_held')
  AND NOT EXISTS (
      SELECT 1 FROM conversation_messages AS held
      WHERE held.session_id = candidate.session_id
        AND held.id <= candidate.id
        AND COALESCE(held.metadata, '{}'::jsonb) ? 'overseer_held'
  )
ORDER BY candidate.id ASC
`

type PollNewUserMessagesParams struct {
	SessionID uuid.UUID   `json:"session_id"`
	AfterID   interface{} `json:"after_id"`
}

func (q *Queries) PollNewUserMessages(ctx context.Context, arg PollNewUserMessagesParams) ([]ConversationMessage, error) {
	rows, err := q.db.Query(ctx, pollNewUserMessages, arg.SessionID, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationMessage{}
	for rows.Next() {
		var i ConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
			&i.DeliveryState,
			&i.ClaimedAt,
			&i.DeliverySequence,
			&i.ClaimToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
