// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ActivityEvent struct {
	ID            int64           `json:"id"`
	SessionID     uuid.UUID       `json:"session_id"`
	EventType     string          `json:"event_type"`
	Summary       string          `json:"summary"`
	Detail        json.RawMessage `json:"detail"`
	CreatedAt     time.Time       `json:"created_at"`
	ClientEventID pgtype.UUID     `json:"client_event_id"`
}

type AgentArtifact struct {
	ID          uuid.UUID       `json:"id"`
	SessionID   uuid.UUID       `json:"session_id"`
	Kind        string          `json:"kind"`
	Content     string          `json:"content"`
	S3Url       string          `json:"s3_url"`
	ContentHash string          `json:"content_hash"`
	Metadata    json.RawMessage `json:"metadata"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type AgentRunWakeIntent struct {
	ID                 uuid.UUID          `json:"id"`
	SessionID          uuid.UUID          `json:"session_id"`
	IdempotencyKey     string             `json:"idempotency_key"`
	MessageID          int64              `json:"message_id"`
	TargetWakeRequests int64              `json:"target_wake_requests"`
	AppliedAt          pgtype.Timestamptz `json:"applied_at"`
	CreatedAt          time.Time          `json:"created_at"`
}

type AgentSession struct {
	ID               uuid.UUID       `json:"id"`
	AgentrunName     string          `json:"agentrun_name"`
	AgentrunNs       string          `json:"agentrun_ns"`
	Phase            string          `json:"phase"`
	CurrentStep      string          `json:"current_step"`
	PendingQuestion  string          `json:"pending_question"`
	Metadata         json.RawMessage `json:"metadata"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	PendingActions   json.RawMessage `json:"pending_actions"`
	PendingInputType string          `json:"pending_input_type"`
	PendingRequestID string          `json:"pending_request_id"`
	ChangeSeq        int64           `json:"change_seq"`
	ConversationSeq  int64           `json:"conversation_seq"`
}

type AuthSession struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
	ExpiresAt        time.Time `json:"expires_at"`
	CreatedAt        time.Time `json:"created_at"`
}

type AuthUser struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	Email        pgtype.Text        `json:"email"`
	Name         string             `json:"name"`
	Picture      string             `json:"picture"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	GoogleID     pgtype.Text        `json:"google_id"`
	Role         string             `json:"role"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

type AuthUserGitIdentity struct {
	UserID                 uuid.UUID `json:"user_id"`
	Name                   string    `json:"name"`
	Email                  string    `json:"email"`
	UpdatedAt              time.Time `json:"updated_at"`
	DisableCoAuthorTrailer bool      `json:"disable_co_author_trailer"`
}

type AuthUserModelDefault struct {
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	Model          string    `json:"model"`
	ReasoningLevel string    `json:"reasoning_level"`
	Disabled       bool      `json:"disabled"`
	UpdatedAt      time.Time `json:"updated_at"`
	AuthMode       string    `json:"auth_mode"`
}

type AuthUserNamespace struct {
	UserID    uuid.UUID `json:"user_id"`
	Namespace string    `json:"namespace"`
	CreatedAt time.Time `json:"created_at"`
}

type AuthUserRoleModel struct {
	UserID    uuid.UUID `json:"user_id"`
	RoleName  string    `json:"role_name"`
	Provider  string    `json:"provider"`
	Model     string    `json:"model"`
	UpdatedAt time.Time `json:"updated_at"`
}

type AuthUserRoleParentModel struct {
	UserID    uuid.UUID `json:"user_id"`
	RoleName  string    `json:"role_name"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ConversationMessage struct {
	ID               int64              `json:"id"`
	SessionID        uuid.UUID          `json:"session_id"`
	Role             string             `json:"role"`
	Content          string             `json:"content"`
	Metadata         json.RawMessage    `json:"metadata"`
	CreatedAt        time.Time          `json:"created_at"`
	DeliveryState    string             `json:"delivery_state"`
	ClaimedAt        pgtype.Timestamptz `json:"claimed_at"`
	DeliverySequence pgtype.Int8        `json:"delivery_sequence"`
	ClaimToken       pgtype.UUID        `json:"claim_token"`
}

type DurableEvent struct {
	TenantID string `json:"tenant_id"`
	RunID    string `json:"run_id"`
	Sequence int64  `json:"sequence"`
	Body     []byte `json:"body"`
}

type DurableRun struct {
	TenantID      string             `json:"tenant_id"`
	RunID         string             `json:"run_id"`
	Revision      int64              `json:"revision"`
	EventSequence int64              `json:"event_sequence"`
	Snapshot      []byte             `json:"snapshot"`
	RetainUntil   pgtype.Timestamptz `json:"retain_until"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	LeaseOwner    pgtype.Text        `json:"lease_owner"`
	LeaseToken    pgtype.Text        `json:"lease_token"`
	LeaseUntil    pgtype.Timestamptz `json:"lease_until"`
}

type Notification struct {
	ID                uuid.UUID `json:"id"`
	UserID            string    `json:"user_id"`
	Type              string    `json:"type"`
	Title             string    `json:"title"`
	Body              string    `json:"body"`
	ResourceType      string    `json:"resource_type"`
	ResourceID        string    `json:"resource_id"`
	ResourceNamespace string    `json:"resource_namespace"`
	ActorID           string    `json:"actor_id"`
	ActorName         string    `json:"actor_name"`
	Read              bool      `json:"read"`
	CreatedAt         time.Time `json:"created_at"`
}

type ProjectContent struct {
	ID               uuid.UUID          `json:"id"`
	ProjectNamespace string             `json:"project_namespace"`
	ProjectName      string             `json:"project_name"`
	Kind             string             `json:"kind"`
	Path             string             `json:"path"`
	MediaType        string             `json:"media_type"`
	CurrentVersion   int32              `json:"current_version"`
	Metadata         json.RawMessage    `json:"metadata"`
	Provenance       json.RawMessage    `json:"provenance"`
	ScanStatus       string             `json:"scan_status"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type ProjectContentAudit struct {
	ID        int64           `json:"id"`
	ContentID uuid.UUID       `json:"content_id"`
	Action    string          `json:"action"`
	Actor     string          `json:"actor"`
	Details   json.RawMessage `json:"details"`
	CreatedAt time.Time       `json:"created_at"`
}

type ProjectContentBlobDeletion struct {
	ObjectKey     string    `json:"object_key"`
	CreatedAt     time.Time `json:"created_at"`
	Attempts      int32     `json:"attempts"`
	LastError     string    `json:"last_error"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
}

type ProjectContentVersion struct {
	ContentID uuid.UUID       `json:"content_id"`
	Version   int32           `json:"version"`
	Content   []byte          `json:"content"`
	Sha256    string          `json:"sha256"`
	Size      int64           `json:"size"`
	Creator   string          `json:"creator"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
	ObjectKey string          `json:"object_key"`
}

type ProjectStateMemory struct {
	ProjectID  string             `json:"project_id"`
	ID         string             `json:"id"`
	Kind       string             `json:"kind"`
	SourceRun  string             `json:"source_run"`
	Embedding  pgvector.Vector    `json:"embedding"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
	Title      string             `json:"title"`
	Body       string             `json:"body"`
	Citations  json.RawMessage    `json:"citations"`
	CommitSha  string             `json:"commit_sha"`
	VerifiedAt time.Time          `json:"verified_at"`
	UseCount   int32              `json:"use_count"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	SearchTsv  interface{}        `json:"search_tsv"`
}

type ProjectStateTask struct {
	ProjectID   string             `json:"project_id"`
	ID          string             `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	Priority    int32              `json:"priority"`
	Assignee    string             `json:"assignee"`
	DependsOn   []string           `json:"depends_on"`
	Labels      []string           `json:"labels"`
	Comments    json.RawMessage    `json:"comments"`
	SourceRun   string             `json:"source_run"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	ClosedAt    pgtype.Timestamptz `json:"closed_at"`
}

type ResourceOwnership struct {
	ID                uuid.UUID `json:"id"`
	ResourceType      string    `json:"resource_type"`
	ResourceID        string    `json:"resource_id"`
	ResourceNamespace string    `json:"resource_namespace"`
	OwnerID           string    `json:"owner_id"`
	CreatedAt         time.Time `json:"created_at"`
}

type ResourceShare struct {
	ID                uuid.UUID `json:"id"`
	ResourceType      string    `json:"resource_type"`
	ResourceID        string    `json:"resource_id"`
	ResourceNamespace string    `json:"resource_namespace"`
	SharedWithUserID  string    `json:"shared_with_user_id"`
	SharedByUserID    string    `json:"shared_by_user_id"`
	Permission        string    `json:"permission"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type SessionInterrupt struct {
	ID          int64              `json:"id"`
	SessionID   uuid.UUID          `json:"session_id"`
	RequestedAt time.Time          `json:"requested_at"`
	RequestedBy string             `json:"requested_by"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
}

type SessionTranscript struct {
	SessionID uuid.UUID `json:"session_id"`
	Data      []byte    `json:"data"`
	ItemCount int32     `json:"item_count"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SlackDraft struct {
	ID           uuid.UUID          `json:"id"`
	SlackAgent   string             `json:"slack_agent"`
	OwnerSubject string             `json:"owner_subject"`
	ChannelID    string             `json:"channel_id"`
	ThreadTs     string             `json:"thread_ts"`
	TargetUser   string             `json:"target_user"`
	IncomingText string             `json:"incoming_text"`
	DraftText    string             `json:"draft_text"`
	Status       string             `json:"status"`
	NotifyMsgTs  string             `json:"notify_msg_ts"`
	CreatedAt    time.Time          `json:"created_at"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
	Namespace    string             `json:"namespace"`
	EditedText   string             `json:"edited_text"`
	Kind         string             `json:"kind"`
	OriginMsgTs  string             `json:"origin_msg_ts"`
	RunName      string             `json:"run_name"`
}

type SlackEvent struct {
	SlackAgent string    `json:"slack_agent"`
	EnvelopeID string    `json:"envelope_id"`
	SeenAt     time.Time `json:"seen_at"`
}

type SlackThread struct {
	SlackAgent   string    `json:"slack_agent"`
	ChannelID    string    `json:"channel_id"`
	ThreadTs     string    `json:"thread_ts"`
	RunNamespace string    `json:"run_namespace"`
	RunName      string    `json:"run_name"`
	Kind         string    `json:"kind"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
