// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const clearPendingAction = `-- name: ClearPendingAction :exec
UPDATE agent_sessions
SET pending_question = '', pending_actions = '[]', pending_input_type = '', pending_request_id = '', phase = $2
WHERE id = $1
`

type ClearPendingActionParams struct {
	ID    uuid.UUID `json:"id"`
	Phase string    `json:"phase"`
}

func (q *Queries) ClearPendingAction(ctx context.Context, arg ClearPendingActionParams) error {
	_, err := q.db.Exec(ctx, clearPendingAction, arg.ID, arg.Phase)
	return err
}

const clearPendingQuestion = `-- name: ClearPendingQuestion :exec
UPDATE agent_sessions
SET pending_question = '', pending_actions = '[]', pending_input_type = '', pending_request_id = '', phase = $2
WHERE id = $1
`

type ClearPendingQuestionParams struct {
	ID    uuid.UUID `json:"id"`
	Phase string    `json:"phase"`
}

func (q *Queries) ClearPendingQuestion(ctx context.Context, arg ClearPendingQuestionParams) error {
	_, err := q.db.Exec(ctx, clearPendingQuestion, arg.ID, arg.Phase)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO agent_sessions (agentrun_name, agentrun_ns, phase, current_step)
VALUES ($1, $2, $3, $4)
RETURNING id, agentrun_name, agentrun_ns, phase, current_step, pending_question, metadata, created_at, updated_at, pending_actions, pending_input_type, pending_request_id
`

type CreateSessionParams struct {
	AgentrunName string `json:"agentrun_name"`
	AgentrunNs   string `json:"agentrun_ns"`
	Phase        string `json:"phase"`
	CurrentStep  string `json:"current_step"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AgentSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.AgentrunName,
		arg.AgentrunNs,
		arg.Phase,
		arg.CurrentStep,
	)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.AgentrunName,
		&i.AgentrunNs,
		&i.Phase,
		&i.CurrentStep,
		&i.PendingQuestion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PendingActions,
		&i.PendingInputType,
		&i.PendingRequestID,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, agentrun_name, agentrun_ns, phase, current_step, pending_question, metadata, created_at, updated_at, pending_actions, pending_input_type, pending_request_id FROM agent_sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (AgentSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.AgentrunName,
		&i.AgentrunNs,
		&i.Phase,
		&i.CurrentStep,
		&i.PendingQuestion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PendingActions,
		&i.PendingInputType,
		&i.PendingRequestID,
	)
	return i, err
}

const getSessionByRun = `-- name: GetSessionByRun :one
SELECT id, agentrun_name, agentrun_ns, phase, current_step, pending_question, metadata, created_at, updated_at, pending_actions, pending_input_type, pending_request_id FROM agent_sessions WHERE agentrun_name = $1 AND agentrun_ns = $2
`

type GetSessionByRunParams struct {
	AgentrunName string `json:"agentrun_name"`
	AgentrunNs   string `json:"agentrun_ns"`
}

func (q *Queries) GetSessionByRun(ctx context.Context, arg GetSessionByRunParams) (AgentSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRun, arg.AgentrunName, arg.AgentrunNs)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.AgentrunName,
		&i.AgentrunNs,
		&i.Phase,
		&i.CurrentStep,
		&i.PendingQuestion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PendingActions,
		&i.PendingInputType,
		&i.PendingRequestID,
	)
	return i, err
}

const listAllSessionMetrics = `-- name: ListAllSessionMetrics :many
SELECT agentrun_name, agentrun_ns, metadata
FROM agent_sessions
WHERE metadata IS NOT NULL AND metadata != '{}'
`

type ListAllSessionMetricsRow struct {
	AgentrunName string          `json:"agentrun_name"`
	AgentrunNs   string          `json:"agentrun_ns"`
	Metadata     json.RawMessage `json:"metadata"`
}

func (q *Queries) ListAllSessionMetrics(ctx context.Context) ([]ListAllSessionMetricsRow, error) {
	rows, err := q.db.Query(ctx, listAllSessionMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSessionMetricsRow{}
	for rows.Next() {
		var i ListAllSessionMetricsRow
		if err := rows.Scan(&i.AgentrunName, &i.AgentrunNs, &i.Metadata); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionMetadata = `-- name: UpdateSessionMetadata :exec
UPDATE agent_sessions SET metadata = $2 WHERE id = $1
`

type UpdateSessionMetadataParams struct {
	ID       uuid.UUID       `json:"id"`
	Metadata json.RawMessage `json:"metadata"`
}

func (q *Queries) UpdateSessionMetadata(ctx context.Context, arg UpdateSessionMetadataParams) error {
	_, err := q.db.Exec(ctx, updateSessionMetadata, arg.ID, arg.Metadata)
	return err
}

const updateSessionPendingAction = `-- name: UpdateSessionPendingAction :exec
UPDATE agent_sessions
SET phase = $2, pending_question = $3, pending_actions = $4, pending_input_type = $5, pending_request_id = $6
WHERE id = $1
`

type UpdateSessionPendingActionParams struct {
	ID               uuid.UUID       `json:"id"`
	Phase            string          `json:"phase"`
	PendingQuestion  string          `json:"pending_question"`
	PendingActions   json.RawMessage `json:"pending_actions"`
	PendingInputType string          `json:"pending_input_type"`
	PendingRequestID string          `json:"pending_request_id"`
}

func (q *Queries) UpdateSessionPendingAction(ctx context.Context, arg UpdateSessionPendingActionParams) error {
	_, err := q.db.Exec(ctx, updateSessionPendingAction,
		arg.ID,
		arg.Phase,
		arg.PendingQuestion,
		arg.PendingActions,
		arg.PendingInputType,
		arg.PendingRequestID,
	)
	return err
}

const updateSessionPendingQuestion = `-- name: UpdateSessionPendingQuestion :exec
UPDATE agent_sessions
SET phase = $2, pending_question = $3, pending_input_type = $4, pending_request_id = $5
WHERE id = $1
`

type UpdateSessionPendingQuestionParams struct {
	ID               uuid.UUID `json:"id"`
	Phase            string    `json:"phase"`
	PendingQuestion  string    `json:"pending_question"`
	PendingInputType string    `json:"pending_input_type"`
	PendingRequestID string    `json:"pending_request_id"`
}

func (q *Queries) UpdateSessionPendingQuestion(ctx context.Context, arg UpdateSessionPendingQuestionParams) error {
	_, err := q.db.Exec(ctx, updateSessionPendingQuestion,
		arg.ID,
		arg.Phase,
		arg.PendingQuestion,
		arg.PendingInputType,
		arg.PendingRequestID,
	)
	return err
}

const updateSessionPhase = `-- name: UpdateSessionPhase :exec
UPDATE agent_sessions
SET phase = $2, current_step = $3
WHERE id = $1
`

type UpdateSessionPhaseParams struct {
	ID          uuid.UUID `json:"id"`
	Phase       string    `json:"phase"`
	CurrentStep string    `json:"current_step"`
}

func (q *Queries) UpdateSessionPhase(ctx context.Context, arg UpdateSessionPhaseParams) error {
	_, err := q.db.Exec(ctx, updateSessionPhase, arg.ID, arg.Phase, arg.CurrentStep)
	return err
}
