// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slack.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimSlackDraft = `-- name: ClaimSlackDraft :one
UPDATE slack_drafts
SET status = $1
WHERE id = $2
  AND namespace = $3
  AND slack_agent = $4
  AND owner_subject = $5
  AND kind = $6
  AND status = 'pending'
RETURNING id, slack_agent, owner_subject, channel_id, thread_ts, target_user, incoming_text, draft_text, status, notify_msg_ts, created_at, decided_at, namespace, edited_text, kind, origin_msg_ts, run_name
`

type ClaimSlackDraftParams struct {
	NextStatus   string    `json:"next_status"`
	ID           uuid.UUID `json:"id"`
	Namespace    string    `json:"namespace"`
	SlackAgent   string    `json:"slack_agent"`
	OwnerSubject string    `json:"owner_subject"`
	Kind         string    `json:"kind"`
}

func (q *Queries) ClaimSlackDraft(ctx context.Context, arg ClaimSlackDraftParams) (SlackDraft, error) {
	row := q.db.QueryRow(ctx, claimSlackDraft,
		arg.NextStatus,
		arg.ID,
		arg.Namespace,
		arg.SlackAgent,
		arg.OwnerSubject,
		arg.Kind,
	)
	var i SlackDraft
	err := row.Scan(
		&i.ID,
		&i.SlackAgent,
		&i.OwnerSubject,
		&i.ChannelID,
		&i.ThreadTs,
		&i.TargetUser,
		&i.IncomingText,
		&i.DraftText,
		&i.Status,
		&i.NotifyMsgTs,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.Namespace,
		&i.EditedText,
		&i.Kind,
		&i.OriginMsgTs,
		&i.RunName,
	)
	return i, err
}

const countSlackDraftsByStatus = `-- name: CountSlackDraftsByStatus :many
SELECT status, COUNT(*) AS count FROM slack_drafts
WHERE slack_agent = $1
GROUP BY status
`

type CountSlackDraftsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountSlackDraftsByStatus(ctx context.Context, slackAgent string) ([]CountSlackDraftsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countSlackDraftsByStatus, slackAgent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSlackDraftsByStatusRow{}
	for rows.Next() {
		var i CountSlackDraftsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSlackDraft = `-- name: CreateSlackDraft :one
INSERT INTO slack_drafts (slack_agent, namespace, owner_subject, channel_id, thread_ts, target_user, incoming_text, draft_text, status, notify_msg_ts, kind, origin_msg_ts, run_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, slack_agent, owner_subject, channel_id, thread_ts, target_user, incoming_text, draft_text, status, notify_msg_ts, created_at, decided_at, namespace, edited_text, kind, origin_msg_ts, run_name
`

type CreateSlackDraftParams struct {
	SlackAgent   string `json:"slack_agent"`
	Namespace    string `json:"namespace"`
	OwnerSubject string `json:"owner_subject"`
	ChannelID    string `json:"channel_id"`
	ThreadTs     string `json:"thread_ts"`
	TargetUser   string `json:"target_user"`
	IncomingText string `json:"incoming_text"`
	DraftText    string `json:"draft_text"`
	Status       string `json:"status"`
	NotifyMsgTs  string `json:"notify_msg_ts"`
	Kind         string `json:"kind"`
	OriginMsgTs  string `json:"origin_msg_ts"`
	RunName      string `json:"run_name"`
}

func (q *Queries) CreateSlackDraft(ctx context.Context, arg CreateSlackDraftParams) (SlackDraft, error) {
	row := q.db.QueryRow(ctx, createSlackDraft,
		arg.SlackAgent,
		arg.Namespace,
		arg.OwnerSubject,
		arg.ChannelID,
		arg.ThreadTs,
		arg.TargetUser,
		arg.IncomingText,
		arg.DraftText,
		arg.Status,
		arg.NotifyMsgTs,
		arg.Kind,
		arg.OriginMsgTs,
		arg.RunName,
	)
	var i SlackDraft
	err := row.Scan(
		&i.ID,
		&i.SlackAgent,
		&i.OwnerSubject,
		&i.ChannelID,
		&i.ThreadTs,
		&i.TargetUser,
		&i.IncomingText,
		&i.DraftText,
		&i.Status,
		&i.NotifyMsgTs,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.Namespace,
		&i.EditedText,
		&i.Kind,
		&i.OriginMsgTs,
		&i.RunName,
	)
	return i, err
}

const getSlackDraft = `-- name: GetSlackDraft :one
SELECT id, slack_agent, owner_subject, channel_id, thread_ts, target_user, incoming_text, draft_text, status, notify_msg_ts, created_at, decided_at, namespace, edited_text, kind, origin_msg_ts, run_name FROM slack_drafts WHERE id = $1
`

func (q *Queries) GetSlackDraft(ctx context.Context, id uuid.UUID) (SlackDraft, error) {
	row := q.db.QueryRow(ctx, getSlackDraft, id)
	var i SlackDraft
	err := row.Scan(
		&i.ID,
		&i.SlackAgent,
		&i.OwnerSubject,
		&i.ChannelID,
		&i.ThreadTs,
		&i.TargetUser,
		&i.IncomingText,
		&i.DraftText,
		&i.Status,
		&i.NotifyMsgTs,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.Namespace,
		&i.EditedText,
		&i.Kind,
		&i.OriginMsgTs,
		&i.RunName,
	)
	return i, err
}

const getSlackThread = `-- name: GetSlackThread :one
SELECT slack_agent, channel_id, thread_ts, run_namespace, run_name, kind, created_at, updated_at FROM slack_threads
WHERE slack_agent = $1 AND channel_id = $2 AND thread_ts = $3
`

type GetSlackThreadParams struct {
	SlackAgent string `json:"slack_agent"`
	ChannelID  string `json:"channel_id"`
	ThreadTs   string `json:"thread_ts"`
}

func (q *Queries) GetSlackThread(ctx context.Context, arg GetSlackThreadParams) (SlackThread, error) {
	row := q.db.QueryRow(ctx, getSlackThread, arg.SlackAgent, arg.ChannelID, arg.ThreadTs)
	var i SlackThread
	err := row.Scan(
		&i.SlackAgent,
		&i.ChannelID,
		&i.ThreadTs,
		&i.RunNamespace,
		&i.RunName,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSlackThreadByRun = `-- name: GetSlackThreadByRun :one
SELECT slack_agent, channel_id, thread_ts, run_namespace, run_name, kind, created_at, updated_at FROM slack_threads
WHERE run_namespace = $1 AND run_name = $2
LIMIT 1
`

type GetSlackThreadByRunParams struct {
	RunNamespace string `json:"run_namespace"`
	RunName      string `json:"run_name"`
}

func (q *Queries) GetSlackThreadByRun(ctx context.Context, arg GetSlackThreadByRunParams) (SlackThread, error) {
	row := q.db.QueryRow(ctx, getSlackThreadByRun, arg.RunNamespace, arg.RunName)
	var i SlackThread
	err := row.Scan(
		&i.SlackAgent,
		&i.ChannelID,
		&i.ThreadTs,
		&i.RunNamespace,
		&i.RunName,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingSlackDrafts = `-- name: ListPendingSlackDrafts :many
SELECT id, slack_agent, owner_subject, channel_id, thread_ts, target_user, incoming_text, draft_text, status, notify_msg_ts, created_at, decided_at, namespace, edited_text, kind, origin_msg_ts, run_name FROM slack_drafts
WHERE slack_agent = $1 AND status = 'pending'
ORDER BY created_at DESC
LIMIT $2
`

type ListPendingSlackDraftsParams struct {
	SlackAgent string `json:"slack_agent"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) ListPendingSlackDrafts(ctx context.Context, arg ListPendingSlackDraftsParams) ([]SlackDraft, error) {
	rows, err := q.db.Query(ctx, listPendingSlackDrafts, arg.SlackAgent, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlackDraft{}
	for rows.Next() {
		var i SlackDraft
		if err := rows.Scan(
			&i.ID,
			&i.SlackAgent,
			&i.OwnerSubject,
			&i.ChannelID,
			&i.ThreadTs,
			&i.TargetUser,
			&i.IncomingText,
			&i.DraftText,
			&i.Status,
			&i.NotifyMsgTs,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.Namespace,
			&i.EditedText,
			&i.Kind,
			&i.OriginMsgTs,
			&i.RunName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlackDraftsByAgent = `-- name: ListSlackDraftsByAgent :many
SELECT id, slack_agent, owner_subject, channel_id, thread_ts, target_user, incoming_text, draft_text, status, notify_msg_ts, created_at, decided_at, namespace, edited_text, kind, origin_msg_ts, run_name FROM slack_drafts
WHERE namespace = $1
  AND slack_agent = $2
  AND ($3::text = '' OR status = $3)
ORDER BY created_at DESC
LIMIT $4
`

type ListSlackDraftsByAgentParams struct {
	Namespace  string `json:"namespace"`
	SlackAgent string `json:"slack_agent"`
	Status     string `json:"status"`
	MaxRows    int32  `json:"max_rows"`
}

func (q *Queries) ListSlackDraftsByAgent(ctx context.Context, arg ListSlackDraftsByAgentParams) ([]SlackDraft, error) {
	rows, err := q.db.Query(ctx, listSlackDraftsByAgent,
		arg.Namespace,
		arg.SlackAgent,
		arg.Status,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlackDraft{}
	for rows.Next() {
		var i SlackDraft
		if err := rows.Scan(
			&i.ID,
			&i.SlackAgent,
			&i.OwnerSubject,
			&i.ChannelID,
			&i.ThreadTs,
			&i.TargetUser,
			&i.IncomingText,
			&i.DraftText,
			&i.Status,
			&i.NotifyMsgTs,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.Namespace,
			&i.EditedText,
			&i.Kind,
			&i.OriginMsgTs,
			&i.RunName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlackDraftsForOwner = `-- name: ListSlackDraftsForOwner :many
SELECT id, slack_agent, owner_subject, channel_id, thread_ts, target_user, incoming_text, draft_text, status, notify_msg_ts, created_at, decided_at, namespace, edited_text, kind, origin_msg_ts, run_name FROM slack_drafts
WHERE owner_subject = $1 AND ($2::text = '' OR status = $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListSlackDraftsForOwnerParams struct {
	OwnerSubject string `json:"owner_subject"`
	Column2      string `json:"column_2"`
	Limit        int32  `json:"limit"`
}

func (q *Queries) ListSlackDraftsForOwner(ctx context.Context, arg ListSlackDraftsForOwnerParams) ([]SlackDraft, error) {
	rows, err := q.db.Query(ctx, listSlackDraftsForOwner, arg.OwnerSubject, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlackDraft{}
	for rows.Next() {
		var i SlackDraft
		if err := rows.Scan(
			&i.ID,
			&i.SlackAgent,
			&i.OwnerSubject,
			&i.ChannelID,
			&i.ThreadTs,
			&i.TargetUser,
			&i.IncomingText,
			&i.DraftText,
			&i.Status,
			&i.NotifyMsgTs,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.Namespace,
			&i.EditedText,
			&i.Kind,
			&i.OriginMsgTs,
			&i.RunName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSlackEventSeen = `-- name: MarkSlackEventSeen :one
INSERT INTO slack_events (slack_agent, envelope_id)
VALUES ($1, $2)
ON CONFLICT (slack_agent, envelope_id) DO NOTHING
RETURNING envelope_id
`

type MarkSlackEventSeenParams struct {
	SlackAgent string `json:"slack_agent"`
	EnvelopeID string `json:"envelope_id"`
}

func (q *Queries) MarkSlackEventSeen(ctx context.Context, arg MarkSlackEventSeenParams) (string, error) {
	row := q.db.QueryRow(ctx, markSlackEventSeen, arg.SlackAgent, arg.EnvelopeID)
	var envelope_id string
	err := row.Scan(&envelope_id)
	return envelope_id, err
}

const pruneSlackEvents = `-- name: PruneSlackEvents :exec
DELETE FROM slack_events WHERE seen_at < $1
`

func (q *Queries) PruneSlackEvents(ctx context.Context, seenAt time.Time) error {
	_, err := q.db.Exec(ctx, pruneSlackEvents, seenAt)
	return err
}

const resolveSlackDraft = `-- name: ResolveSlackDraft :exec
UPDATE slack_drafts
SET status = $1, draft_text = $2, decided_at = now()
WHERE id = $3 AND status = $4
`

type ResolveSlackDraftParams struct {
	Status         string    `json:"status"`
	DraftText      string    `json:"draft_text"`
	ID             uuid.UUID `json:"id"`
	ExpectedStatus string    `json:"expected_status"`
}

func (q *Queries) ResolveSlackDraft(ctx context.Context, arg ResolveSlackDraftParams) error {
	_, err := q.db.Exec(ctx, resolveSlackDraft,
		arg.Status,
		arg.DraftText,
		arg.ID,
		arg.ExpectedStatus,
	)
	return err
}

const resolveSlackDraftEdited = `-- name: ResolveSlackDraftEdited :exec
UPDATE slack_drafts
SET status = $1, edited_text = $2, decided_at = now()
WHERE id = $3 AND status = $4
`

type ResolveSlackDraftEditedParams struct {
	Status         string    `json:"status"`
	EditedText     string    `json:"edited_text"`
	ID             uuid.UUID `json:"id"`
	ExpectedStatus string    `json:"expected_status"`
}

func (q *Queries) ResolveSlackDraftEdited(ctx context.Context, arg ResolveSlackDraftEditedParams) error {
	_, err := q.db.Exec(ctx, resolveSlackDraftEdited,
		arg.Status,
		arg.EditedText,
		arg.ID,
		arg.ExpectedStatus,
	)
	return err
}

const setSlackDraftNotifyTS = `-- name: SetSlackDraftNotifyTS :exec
UPDATE slack_drafts SET notify_msg_ts = $2 WHERE id = $1
`

type SetSlackDraftNotifyTSParams struct {
	ID          uuid.UUID `json:"id"`
	NotifyMsgTs string    `json:"notify_msg_ts"`
}

func (q *Queries) SetSlackDraftNotifyTS(ctx context.Context, arg SetSlackDraftNotifyTSParams) error {
	_, err := q.db.Exec(ctx, setSlackDraftNotifyTS, arg.ID, arg.NotifyMsgTs)
	return err
}

const updateSlackDraftText = `-- name: UpdateSlackDraftText :exec
UPDATE slack_drafts
SET draft_text = $1, status = $2, decided_at = NULL
WHERE id = $3 AND status = $4
`

type UpdateSlackDraftTextParams struct {
	DraftText      string    `json:"draft_text"`
	NextStatus     string    `json:"next_status"`
	ID             uuid.UUID `json:"id"`
	ExpectedStatus string    `json:"expected_status"`
}

func (q *Queries) UpdateSlackDraftText(ctx context.Context, arg UpdateSlackDraftTextParams) error {
	_, err := q.db.Exec(ctx, updateSlackDraftText,
		arg.DraftText,
		arg.NextStatus,
		arg.ID,
		arg.ExpectedStatus,
	)
	return err
}

const upsertSlackThread = `-- name: UpsertSlackThread :exec
INSERT INTO slack_threads (slack_agent, channel_id, thread_ts, run_namespace, run_name, kind)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (slack_agent, channel_id, thread_ts) DO UPDATE SET
    run_namespace = EXCLUDED.run_namespace,
    run_name = EXCLUDED.run_name,
    kind = EXCLUDED.kind,
    updated_at = now()
`

type UpsertSlackThreadParams struct {
	SlackAgent   string `json:"slack_agent"`
	ChannelID    string `json:"channel_id"`
	ThreadTs     string `json:"thread_ts"`
	RunNamespace string `json:"run_namespace"`
	RunName      string `json:"run_name"`
	Kind         string `json:"kind"`
}

func (q *Queries) UpsertSlackThread(ctx context.Context, arg UpsertSlackThreadParams) error {
	_, err := q.db.Exec(ctx, upsertSlackThread,
		arg.SlackAgent,
		arg.ChannelID,
		arg.ThreadTs,
		arg.RunNamespace,
		arg.RunName,
		arg.Kind,
	)
	return err
}
