// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: rpc/auth/service.proto

package authconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	auth "github.com/gratefulagents/gratefulagents/rpc/auth"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "auth.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/auth.v1.AuthService/Login"
	// AuthServiceRefreshTokenProcedure is the fully-qualified name of the AuthService's RefreshToken
	// RPC.
	AuthServiceRefreshTokenProcedure = "/auth.v1.AuthService/RefreshToken"
	// AuthServiceLogoutProcedure is the fully-qualified name of the AuthService's Logout RPC.
	AuthServiceLogoutProcedure = "/auth.v1.AuthService/Logout"
	// AuthServiceGetCurrentUserProcedure is the fully-qualified name of the AuthService's
	// GetCurrentUser RPC.
	AuthServiceGetCurrentUserProcedure = "/auth.v1.AuthService/GetCurrentUser"
	// AuthServiceSearchUsersProcedure is the fully-qualified name of the AuthService's SearchUsers RPC.
	AuthServiceSearchUsersProcedure = "/auth.v1.AuthService/SearchUsers"
	// AuthServiceListUsersProcedure is the fully-qualified name of the AuthService's ListUsers RPC.
	AuthServiceListUsersProcedure = "/auth.v1.AuthService/ListUsers"
	// AuthServiceUpdateUserRoleProcedure is the fully-qualified name of the AuthService's
	// UpdateUserRole RPC.
	AuthServiceUpdateUserRoleProcedure = "/auth.v1.AuthService/UpdateUserRole"
	// AuthServiceDeleteUserProcedure is the fully-qualified name of the AuthService's DeleteUser RPC.
	AuthServiceDeleteUserProcedure = "/auth.v1.AuthService/DeleteUser"
	// AuthServiceGetJWKSProcedure is the fully-qualified name of the AuthService's GetJWKS RPC.
	AuthServiceGetJWKSProcedure = "/auth.v1.AuthService/GetJWKS"
)

// AuthServiceClient is a client for the auth.v1.AuthService service.
type AuthServiceClient interface {
	// Login authenticates via Google OAuth ID token or username/password.
	Login(context.Context, *connect.Request[auth.LoginRequest]) (*connect.Response[auth.LoginResponse], error)
	// RefreshToken exchanges a valid refresh token for a new access + refresh pair.
	RefreshToken(context.Context, *connect.Request[auth.RefreshTokenRequest]) (*connect.Response[auth.RefreshTokenResponse], error)
	// Logout invalidates the given refresh token.
	Logout(context.Context, *connect.Request[auth.LogoutRequest]) (*connect.Response[auth.LogoutResponse], error)
	// GetCurrentUser returns the authenticated user's profile.
	GetCurrentUser(context.Context, *connect.Request[auth.GetCurrentUserRequest]) (*connect.Response[auth.User], error)
	// SearchUsers finds users by username or name substring.
	SearchUsers(context.Context, *connect.Request[auth.SearchUsersRequest]) (*connect.Response[auth.SearchUsersResponse], error)
	// ListUsers returns all registered users. Admin only.
	ListUsers(context.Context, *connect.Request[auth.ListUsersRequest]) (*connect.Response[auth.ListUsersResponse], error)
	// UpdateUserRole changes a user's role (admin/member/viewer). Admin only.
	UpdateUserRole(context.Context, *connect.Request[auth.UpdateUserRoleRequest]) (*connect.Response[auth.User], error)
	// DeleteUser permanently removes a user account. Admin only.
	DeleteUser(context.Context, *connect.Request[auth.DeleteUserRequest]) (*connect.Response[auth.DeleteUserResponse], error)
	// GetJWKS returns the JSON Web Key Set used to verify access tokens.
	GetJWKS(context.Context, *connect.Request[auth.GetJWKSRequest]) (*connect.Response[auth.GetJWKSResponse], error)
}

// NewAuthServiceClient constructs a client for the auth.v1.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := auth.File_rpc_auth_service_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		login: connect.NewClient[auth.LoginRequest, auth.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		refreshToken: connect.NewClient[auth.RefreshTokenRequest, auth.RefreshTokenResponse](
			httpClient,
			baseURL+AuthServiceRefreshTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[auth.LogoutRequest, auth.LogoutResponse](
			httpClient,
			baseURL+AuthServiceLogoutProcedure,
			connect.WithSchema(authServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
		getCurrentUser: connect.NewClient[auth.GetCurrentUserRequest, auth.User](
			httpClient,
			baseURL+AuthServiceGetCurrentUserProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetCurrentUser")),
			connect.WithClientOptions(opts...),
		),
		searchUsers: connect.NewClient[auth.SearchUsersRequest, auth.SearchUsersResponse](
			httpClient,
			baseURL+AuthServiceSearchUsersProcedure,
			connect.WithSchema(authServiceMethods.ByName("SearchUsers")),
			connect.WithClientOptions(opts...),
		),
		listUsers: connect.NewClient[auth.ListUsersRequest, auth.ListUsersResponse](
			httpClient,
			baseURL+AuthServiceListUsersProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		updateUserRole: connect.NewClient[auth.UpdateUserRoleRequest, auth.User](
			httpClient,
			baseURL+AuthServiceUpdateUserRoleProcedure,
			connect.WithSchema(authServiceMethods.ByName("UpdateUserRole")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[auth.DeleteUserRequest, auth.DeleteUserResponse](
			httpClient,
			baseURL+AuthServiceDeleteUserProcedure,
			connect.WithSchema(authServiceMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
		getJWKS: connect.NewClient[auth.GetJWKSRequest, auth.GetJWKSResponse](
			httpClient,
			baseURL+AuthServiceGetJWKSProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetJWKS")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	login          *connect.Client[auth.LoginRequest, auth.LoginResponse]
	refreshToken   *connect.Client[auth.RefreshTokenRequest, auth.RefreshTokenResponse]
	logout         *connect.Client[auth.LogoutRequest, auth.LogoutResponse]
	getCurrentUser *connect.Client[auth.GetCurrentUserRequest, auth.User]
	searchUsers    *connect.Client[auth.SearchUsersRequest, auth.SearchUsersResponse]
	listUsers      *connect.Client[auth.ListUsersRequest, auth.ListUsersResponse]
	updateUserRole *connect.Client[auth.UpdateUserRoleRequest, auth.User]
	deleteUser     *connect.Client[auth.DeleteUserRequest, auth.DeleteUserResponse]
	getJWKS        *connect.Client[auth.GetJWKSRequest, auth.GetJWKSResponse]
}

// Login calls auth.v1.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[auth.LoginRequest]) (*connect.Response[auth.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// RefreshToken calls auth.v1.AuthService.RefreshToken.
func (c *authServiceClient) RefreshToken(ctx context.Context, req *connect.Request[auth.RefreshTokenRequest]) (*connect.Response[auth.RefreshTokenResponse], error) {
	return c.refreshToken.CallUnary(ctx, req)
}

// Logout calls auth.v1.AuthService.Logout.
func (c *authServiceClient) Logout(ctx context.Context, req *connect.Request[auth.LogoutRequest]) (*connect.Response[auth.LogoutResponse], error) {
	return c.logout.CallUnary(ctx, req)
}

// GetCurrentUser calls auth.v1.AuthService.GetCurrentUser.
func (c *authServiceClient) GetCurrentUser(ctx context.Context, req *connect.Request[auth.GetCurrentUserRequest]) (*connect.Response[auth.User], error) {
	return c.getCurrentUser.CallUnary(ctx, req)
}

// SearchUsers calls auth.v1.AuthService.SearchUsers.
func (c *authServiceClient) SearchUsers(ctx context.Context, req *connect.Request[auth.SearchUsersRequest]) (*connect.Response[auth.SearchUsersResponse], error) {
	return c.searchUsers.CallUnary(ctx, req)
}

// ListUsers calls auth.v1.AuthService.ListUsers.
func (c *authServiceClient) ListUsers(ctx context.Context, req *connect.Request[auth.ListUsersRequest]) (*connect.Response[auth.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// UpdateUserRole calls auth.v1.AuthService.UpdateUserRole.
func (c *authServiceClient) UpdateUserRole(ctx context.Context, req *connect.Request[auth.UpdateUserRoleRequest]) (*connect.Response[auth.User], error) {
	return c.updateUserRole.CallUnary(ctx, req)
}

// DeleteUser calls auth.v1.AuthService.DeleteUser.
func (c *authServiceClient) DeleteUser(ctx context.Context, req *connect.Request[auth.DeleteUserRequest]) (*connect.Response[auth.DeleteUserResponse], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// GetJWKS calls auth.v1.AuthService.GetJWKS.
func (c *authServiceClient) GetJWKS(ctx context.Context, req *connect.Request[auth.GetJWKSRequest]) (*connect.Response[auth.GetJWKSResponse], error) {
	return c.getJWKS.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the auth.v1.AuthService service.
type AuthServiceHandler interface {
	// Login authenticates via Google OAuth ID token or username/password.
	Login(context.Context, *connect.Request[auth.LoginRequest]) (*connect.Response[auth.LoginResponse], error)
	// RefreshToken exchanges a valid refresh token for a new access + refresh pair.
	RefreshToken(context.Context, *connect.Request[auth.RefreshTokenRequest]) (*connect.Response[auth.RefreshTokenResponse], error)
	// Logout invalidates the given refresh token.
	Logout(context.Context, *connect.Request[auth.LogoutRequest]) (*connect.Response[auth.LogoutResponse], error)
	// GetCurrentUser returns the authenticated user's profile.
	GetCurrentUser(context.Context, *connect.Request[auth.GetCurrentUserRequest]) (*connect.Response[auth.User], error)
	// SearchUsers finds users by username or name substring.
	SearchUsers(context.Context, *connect.Request[auth.SearchUsersRequest]) (*connect.Response[auth.SearchUsersResponse], error)
	// ListUsers returns all registered users. Admin only.
	ListUsers(context.Context, *connect.Request[auth.ListUsersRequest]) (*connect.Response[auth.ListUsersResponse], error)
	// UpdateUserRole changes a user's role (admin/member/viewer). Admin only.
	UpdateUserRole(context.Context, *connect.Request[auth.UpdateUserRoleRequest]) (*connect.Response[auth.User], error)
	// DeleteUser permanently removes a user account. Admin only.
	DeleteUser(context.Context, *connect.Request[auth.DeleteUserRequest]) (*connect.Response[auth.DeleteUserResponse], error)
	// GetJWKS returns the JSON Web Key Set used to verify access tokens.
	GetJWKS(context.Context, *connect.Request[auth.GetJWKSRequest]) (*connect.Response[auth.GetJWKSResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := auth.File_rpc_auth_service_proto.Services().ByName("AuthService").Methods()
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRefreshTokenHandler := connect.NewUnaryHandler(
		AuthServiceRefreshTokenProcedure,
		svc.RefreshToken,
		connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLogoutHandler := connect.NewUnaryHandler(
		AuthServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(authServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetCurrentUserHandler := connect.NewUnaryHandler(
		AuthServiceGetCurrentUserProcedure,
		svc.GetCurrentUser,
		connect.WithSchema(authServiceMethods.ByName("GetCurrentUser")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceSearchUsersHandler := connect.NewUnaryHandler(
		AuthServiceSearchUsersProcedure,
		svc.SearchUsers,
		connect.WithSchema(authServiceMethods.ByName("SearchUsers")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListUsersHandler := connect.NewUnaryHandler(
		AuthServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(authServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceUpdateUserRoleHandler := connect.NewUnaryHandler(
		AuthServiceUpdateUserRoleProcedure,
		svc.UpdateUserRole,
		connect.WithSchema(authServiceMethods.ByName("UpdateUserRole")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceDeleteUserHandler := connect.NewUnaryHandler(
		AuthServiceDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(authServiceMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetJWKSHandler := connect.NewUnaryHandler(
		AuthServiceGetJWKSProcedure,
		svc.GetJWKS,
		connect.WithSchema(authServiceMethods.ByName("GetJWKS")),
		connect.WithHandlerOptions(opts...),
	)
	return "/auth.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		case AuthServiceRefreshTokenProcedure:
			authServiceRefreshTokenHandler.ServeHTTP(w, r)
		case AuthServiceLogoutProcedure:
			authServiceLogoutHandler.ServeHTTP(w, r)
		case AuthServiceGetCurrentUserProcedure:
			authServiceGetCurrentUserHandler.ServeHTTP(w, r)
		case AuthServiceSearchUsersProcedure:
			authServiceSearchUsersHandler.ServeHTTP(w, r)
		case AuthServiceListUsersProcedure:
			authServiceListUsersHandler.ServeHTTP(w, r)
		case AuthServiceUpdateUserRoleProcedure:
			authServiceUpdateUserRoleHandler.ServeHTTP(w, r)
		case AuthServiceDeleteUserProcedure:
			authServiceDeleteUserHandler.ServeHTTP(w, r)
		case AuthServiceGetJWKSProcedure:
			authServiceGetJWKSHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[auth.LoginRequest]) (*connect.Response[auth.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) RefreshToken(context.Context, *connect.Request[auth.RefreshTokenRequest]) (*connect.Response[auth.RefreshTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.RefreshToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) Logout(context.Context, *connect.Request[auth.LogoutRequest]) (*connect.Response[auth.LogoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.Logout is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetCurrentUser(context.Context, *connect.Request[auth.GetCurrentUserRequest]) (*connect.Response[auth.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.GetCurrentUser is not implemented"))
}

func (UnimplementedAuthServiceHandler) SearchUsers(context.Context, *connect.Request[auth.SearchUsersRequest]) (*connect.Response[auth.SearchUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.SearchUsers is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListUsers(context.Context, *connect.Request[auth.ListUsersRequest]) (*connect.Response[auth.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.ListUsers is not implemented"))
}

func (UnimplementedAuthServiceHandler) UpdateUserRole(context.Context, *connect.Request[auth.UpdateUserRoleRequest]) (*connect.Response[auth.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.UpdateUserRole is not implemented"))
}

func (UnimplementedAuthServiceHandler) DeleteUser(context.Context, *connect.Request[auth.DeleteUserRequest]) (*connect.Response[auth.DeleteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.DeleteUser is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetJWKS(context.Context, *connect.Request[auth.GetJWKSRequest]) (*connect.Response[auth.GetJWKSResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.GetJWKS is not implemented"))
}
